import { useState } from "react";
import { NavLink, useLocation, useParams } from "react-router-dom";
import { AlertTriangle, ArrowLeft, BriefcaseBusiness, Building2, CheckCircle2, ClipboardCheck, GraduationCap, HeartHandshake, LockKeyhole, Plus, Search, ShieldCheck, UserCheck, UserPlus, UsersRound } from "lucide-react";
import { buddyPlans, facilitiesRequests, interviewerPortalItems, managerRecruitingItems, mobilityOpportunities, referrerCases, type JourneyStatus } from "../data/fullSystem";
import { usePrototype } from "../prototype/PrototypeContext";
import { Pill, PrototypeBanner, ScreenId } from "./Common";

type PortalKind = "referrer" | "facilities" | "manager-recruiting" | "interviewer" | "buddy" | "mobility";

const portalMeta: Record<PortalKind, { name: string; subtitle: string; home: string; icon: typeof UserPlus }> = {
  referrer: { name: "Employee referrals", subtitle: "Permission, progress and rewards", home: "/referrer", icon: UserPlus },
  facilities: { name: "Workplace readiness", subtitle: "Site, badge, desk and physical access", home: "/facilities", icon: Building2 },
  "manager-recruiting": { name: "Manager recruiting", subtitle: "Requisitions, evidence and decisions", home: "/manager/recruiting", icon: BriefcaseBusiness },
  interviewer: { name: "My interviews", subtitle: "Briefing, schedule and independent evidence", home: "/interviewer", icon: UserCheck },
  buddy: { name: "Buddy experience", subtitle: "Connection, context and check-ins", home: "/buddy", icon: HeartHandshake },
  mobility: { name: "Internal opportunities", subtitle: "Private discovery and consent", home: "/mobility", icon: GraduationCap },
};

function statusTone(state: JourneyStatus | string) {
  if (["Complete", "Active", "Ready"].includes(state)) return "success" as const;
  if (["Blocked", "Cancelled"].includes(state)) return "danger" as const;
  return "warning" as const;
}

function PortalShell({ kind, children }: { kind: PortalKind; children: React.ReactNode }) {
  const meta = portalMeta[kind];
  const Icon = meta.icon;
  return <div className={`role-portal v3-role-portal ${kind}-portal`}><PrototypeBanner /><header className="role-portal-header"><NavLink className="role-portal-brand" to={meta.home}><span className="role-portal-mark"><Icon size={22} /></span><span><strong>{meta.name}</strong><small>{meta.subtitle}</small></span></NavLink><nav aria-label={`${meta.name} navigation`}><NavLink end to={meta.home}>Home</NavLink>{kind === "referrer" && <NavLink to="/referrer/new">New referral</NavLink>}{kind === "facilities" && <NavLink to="/facilities">Requests</NavLink>}{kind === "manager-recruiting" && <NavLink to="/manager">Onboarding readiness</NavLink>}{kind === "mobility" && <NavLink to="/careers">External careers</NavLink>}<button className="role-support-link" onClick={() => { const footer = document.getElementById("portal-support"); if (footer) { footer.tabIndex = -1; footer.focus(); footer.scrollIntoView({ behavior: "smooth" }); } }}>Support</button></nav><Pill tone="info">Synthetic scoped portal</Pill></header><main id="main-content" className="role-portal-main">{children}</main><footer id="portal-support" className="role-portal-footer"><ShieldCheck size={18} /><span><strong>Minimum-necessary wireframe</strong>Every action is synthetic, memory-only and permission scoped.</span></footer></div>;
}

function ReferrerPortal() {
  const { referralId } = useParams();
  const location = useLocation();
  const { announce } = usePrototype();
  const item = referrerCases.find((row) => row.id === referralId);
  const creating = location.pathname.endsWith("/new");
  const disputing = location.pathname.endsWith("/dispute");
  const [saved, setSaved] = useState(false);
  const [permission, setPermission] = useState(false);
  const [query, setQuery] = useState("");
  if (creating) return <PortalShell kind="referrer"><NavLink className="back-link" to="/referrer"><ArrowLeft size={15} /> Referrals</NavLink><section className="panel portal-form-page"><ScreenId>UI-REF-001</ScreenId><span className="eyebrow">Candidate permission before submission</span><h1>Refer someone without creating an application.</h1>{saved ? <div className="completion-receipt"><CheckCircle2 size={23} /><div><strong>Referral REF-MEM-001 created</strong><span>Invitation only · candidate chooses whether to continue.</span></div></div> : <form className="portal-form" onSubmit={(e) => { e.preventDefault(); setSaved(true); announce("Referral invitation created in browser memory."); }}><div className="form-grid"><label>Job<select><option>Senior Product Designer</option><option>Staff Data Platform Engineer</option><option>Recruiting Operations Partner</option></select></label><label>Candidate fixture<select><option>Maya Chen · synthetic</option><option>Noah Williams · synthetic</option></select></label><label>Relationship<select><option>Former colleague</option><option>Professional community</option><option>Previous manager</option><option>University peer</option></select></label><label>How long have you known them?<select><option>Less than 1 year</option><option>1–3 years</option><option>More than 3 years</option></select></label><label className="full">Context<textarea defaultValue="Prepared synthetic professional context; no protected or private information." /></label><label className="full checkbox-row"><input type="checkbox" checked={permission} onChange={(e) => setPermission(e.target.checked)} />I have permission to send this person a referral invitation.</label></div><button disabled={!permission} className="primary-button" type="submit">Create referral invitation</button></form>}</section></PortalShell>;
  if (referralId && !item) return <PortalShell kind="referrer"><section className="role-access-denied"><LockKeyhole size={28} /><h1>Referral unavailable</h1><p>This referral is outside the current employee relationship.</p><NavLink className="primary-button" to="/referrer">Return to referrals</NavLink></section></PortalShell>;
  if (item && disputing) return <PortalShell kind="referrer"><NavLink className="back-link" to={`/referrer/${item.id}`}><ArrowLeft size={15} /> Referral</NavLink><section className="panel portal-form-page"><ScreenId>UI-REF-001</ScreenId><h1>Request a reward review.</h1><p>A commercial dispute cannot change candidate evaluation or reveal candidate outcomes.</p>{saved ? <div className="completion-receipt"><CheckCircle2 size={23} /><div><strong>Dispute RWD-MEM-001 opened</strong><span>Reward policy evidence only · candidate data excluded</span></div></div> : <form className="portal-form" onSubmit={(e) => { e.preventDefault(); setSaved(true); announce(`${item.id} reward dispute opened in memory.`); }}><label>Review reason<select><option>Eligibility appears incorrect</option><option>Milestone is missing</option><option>Payment status is stale</option><option>Relationship attribution issue</option></select></label><label>Supporting context<textarea defaultValue="Prepared synthetic reward evidence." /></label><label className="checkbox-row"><input type="checkbox" required />I understand this review does not affect the candidate process.</label><button className="primary-button" type="submit">Submit reward review</button></form>}</section></PortalShell>;
  if (item) return <PortalShell kind="referrer"><NavLink className="back-link" to="/referrer"><ArrowLeft size={15} /> Referrals</NavLink><section className="role-portal-hero compact"><div><ScreenId>UI-REF-001</ScreenId><span className="eyebrow">{item.id} · {item.relationship}</span><h1>{item.candidate}</h1><p>{item.job}</p></div><Pill tone={statusTone(item.status)}>{item.status}</Pill></section><div className="role-dashboard-grid"><section className="panel"><h2>Referral progress</h2><dl className="case-fact-grid"><div><dt>Permission</dt><dd>{item.permission}</dd></div><div><dt>Milestone</dt><dd>{item.milestone}</dd></div><div><dt>Reward</dt><dd>{item.reward}</dd></div><div><dt>Dispute</dt><dd>{item.dispute}</dd></div></dl><ol className="task-step-list"><li><span>1</span>Candidate permission</li><li><span>2</span>Separate application choice</li><li><span>3</span>Eligible start milestone</li><li><span>4</span>Retention and payment review</li></ol><div className="detail-action-strip"><button className="secondary-button" onClick={() => announce(`${item.id} candidate-permission reminder preview opened.`)}>Preview permission reminder</button><NavLink className="primary-button" to={`/referrer/${item.id}/dispute`}>Request reward review</NavLink></div></section><aside className="panel manager-privacy"><LockKeyhole size={22} /><h2>What stays hidden</h2><p>Interview feedback, ranking, decision rationale, background information and other applicants never appear in the referral portal.</p></aside></div></PortalShell>;
  const rows = referrerCases.filter((row) => `${row.candidate} ${row.job} ${row.id}`.toLowerCase().includes(query.toLowerCase()));
  return <PortalShell kind="referrer"><section className="role-portal-hero"><div><ScreenId>UI-REF-001</ScreenId><span className="eyebrow">Employee referral portal</span><h1>Recommend with permission. Track without influence.</h1><p>Candidate choice, relationship, progress and reward are explicit and separated.</p></div><NavLink className="primary-button" to="/referrer/new"><Plus size={16} /> New referral</NavLink></section><section className="panel role-record-list"><div className="table-toolbar"><label><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search referrals" /></label><Pill tone="info">{rows.length} referrals</Pill></div>{rows.map((row) => <NavLink to={`/referrer/${row.id}`} key={row.id}><span className="role-portal-record-icon"><UserPlus size={18} /></span><span><strong>{row.candidate}</strong><small>{row.id} · {row.job}</small></span><span><strong>{row.milestone}</strong><small>{row.reward}</small></span><Pill tone={statusTone(row.status)}>{row.status}</Pill></NavLink>)}</section></PortalShell>;
}

function FacilitiesPortal() {
  const { requestId } = useParams();
  const { announce } = usePrototype();
  const item = facilitiesRequests.find((row) => row.id === requestId);
  const [state, setState] = useState(item?.status ?? "Ready");
  const [evidence, setEvidence] = useState(false);
  const [filter, setFilter] = useState("All");
  if (requestId && !item) return <PortalShell kind="facilities"><section className="role-access-denied"><LockKeyhole size={28} /><h1>Facilities request unavailable</h1><p>This request may belong to another function or site.</p><NavLink className="primary-button" to="/facilities">Return to requests</NavLink></section></PortalShell>;
  if (item) return <PortalShell kind="facilities"><NavLink className="back-link" to="/facilities"><ArrowLeft size={15} /> Facilities queue</NavLink><section className="role-portal-hero compact"><div><ScreenId>UI-FAC-001</ScreenId><span className="eyebrow">{item.id} · {item.site}</span><h1>{item.item}</h1><p>{item.newHire} · due {item.due}</p></div><Pill tone={statusTone(state)}>{state}</Pill></section><div className="role-dashboard-grid"><section className="panel"><h2>Physical-access contract</h2><dl className="case-fact-grid"><div><dt>Site</dt><dd>{item.site}</dd></div><div><dt>Access</dt><dd>{item.accessLevel}</dd></div><div><dt>Dependency</dt><dd>{item.dependency}</dd></div><div><dt>Cancellation</dt><dd>{item.cancellation}</dd></div></dl><label className="checkbox-row"><input type="checkbox" checked={evidence} onChange={(e) => setEvidence(e.target.checked)} />Destination badge/desk receipt verified.</label><div className="detail-action-strip"><button disabled={!evidence || state === "Complete"} className="primary-button" onClick={() => { setState("Complete"); announce(`${item.id} completed with physical-access receipt in memory.`); }}>Mark ready</button><button className="secondary-button" onClick={() => { setState("Cancelled"); announce(`${item.id} revocation preview completed.`); }}>Cancel and revoke</button></div></section><aside className="panel"><ShieldCheck size={24} /><h2>Minimum necessary</h2><p>Facilities sees site, effective date, access level and delivery evidence—not recruiting feedback, compensation, tax or background data.</p></aside></div></PortalShell>;
  const rows = facilitiesRequests.filter((row) => filter === "All" || row.status === filter);
  return <PortalShell kind="facilities"><section className="role-portal-hero"><div><ScreenId>UI-FAC-001</ScreenId><span className="eyebrow">Facilities operations</span><h1>Ready spaces. Revocable access.</h1><p>Desk, badge, site and physical-access work with effective dates and cancellation evidence.</p></div><Pill tone="info">{facilitiesRequests.length} requests</Pill></section><section className="role-summary-cards"><article><Building2 size={22} /><strong>{facilitiesRequests.length}</strong><span>Requests</span></article><article><AlertTriangle size={22} /><strong>{facilitiesRequests.filter((r) => r.status === "Blocked").length}</strong><span>Blocked</span></article><article><CheckCircle2 size={22} /><strong>{facilitiesRequests.filter((r) => r.status === "Complete").length}</strong><span>Complete</span></article><article><ShieldCheck size={22} /><strong>100%</strong><span>Revocation-owned</span></article></section><section className="panel role-record-list"><div className="table-toolbar"><label>Status<select value={filter} onChange={(e) => setFilter(e.target.value)}><option>All</option><option>Ready</option><option>Active</option><option>Blocked</option><option>Complete</option><option>Cancelled</option></select></label><Pill tone="info">{rows.length} visible</Pill></div>{rows.map((row) => <NavLink to={`/facilities/requests/${row.id}`} key={row.id}><span className="role-portal-record-icon"><Building2 size={18} /></span><span><strong>{row.item}</strong><small>{row.id} · {row.newHire}</small></span><span><strong>{row.site}</strong><small>Due {row.due}</small></span><Pill tone={statusTone(row.status)}>{row.status}</Pill></NavLink>)}</section></PortalShell>;
}

function ManagerRecruitingPortal() {
  const { itemId } = useParams();
  const { announce } = usePrototype();
  const item = managerRecruitingItems.find((row) => row.id === itemId);
  const [decision, setDecision] = useState<string | null>(null);
  const [confirmed, setConfirmed] = useState(false);
  if (itemId && !item) return <PortalShell kind="manager-recruiting"><section className="role-access-denied"><LockKeyhole size={28} /><h1>Recruiting work is outside this manager scope</h1><NavLink className="primary-button" to="/manager/recruiting">Return to work</NavLink></section></PortalShell>;
  if (item?.id === "REQ-DEMO-001") return <PortalShell kind="manager-recruiting"><NavLink className="back-link" to="/manager/recruiting"><ArrowLeft size={15} /> Manager work</NavLink><section className="role-portal-hero compact"><div><ScreenId>UI-MGR-002</ScreenId><span className="eyebrow">REQ-DEMO-001 · Requisition</span><h1>Senior Product Designer</h1><p>Manager-owned demand · due Today</p></div><Pill tone="warning">Draft v3</Pill></section><div className="role-dashboard-grid bc01-requisition-product"><section className="panel"><div className="panel-heading"><div><h2>Governed demand</h2><span>Exact-version submission</span></div><Pill tone="warning">Draft v3</Pill></div><div className="object-form-grid"><label><span>Workforce plan</span><input readOnly value="FY27 Product expansion" /></label><label><span>Position</span><input readOnly value="Senior Product Designer" /></label><label><span>Location</span><input readOnly value="California · Remote" /></label><label><span>Approved openings</span><input readOnly value="2 · OPN-001 and OPN-002" /></label><label><span>Target start</span><input readOnly value="November 16, 2026" /></label><label><span>Budget reference</span><input readOnly value="HC-FY27-041 · current" /></label><label className="full-field"><span>Business justification</span><textarea readOnly value="Expand accessible product-design capacity for the FY27 roadmap." /></label></div><div className="field-assurance"><ShieldCheck size={16} />Current plan, manager relationship, duplicate demand and required evidence are checked before submission.</div><NavLink className="primary-button" to="/demo/workbench/uc-01?feature=WF-P0-03">Continue to exact-version submission</NavLink></section><aside className="panel manager-privacy"><LockKeyhole size={22} /><h2>Manager boundary</h2><p>The manager creates and submits demand. Finance and Compensation independently approve the exact version; the manager cannot self-approve it.</p><dl className="case-fact-grid"><div><dt>Visible</dt><dd>Plan, position, location, openings, target date and justification</dd></div><div><dt>Purpose-bound</dt><dd>Budget reference only</dd></div><div><dt>Hidden</dt><dd>Other jobs, candidate data and approver-only evidence</dd></div></dl></aside></div></PortalShell>;
  if (item) return <PortalShell kind="manager-recruiting"><NavLink className="back-link" to="/manager/recruiting"><ArrowLeft size={15} /> Manager work</NavLink><section className="role-portal-hero compact"><div><ScreenId>UI-MGR-002</ScreenId><span className="eyebrow">{item.id} · {item.type}</span><h1>{item.job}</h1><p>{item.candidate} · due {item.due}</p></div><Pill tone={statusTone(decision ? "Complete" : item.status)}>{decision ?? item.status}</Pill></section><div className="role-dashboard-grid"><section className="panel"><h2>{item.type} evidence</h2><dl className="case-fact-grid"><div><dt>Required evidence</dt><dd>{item.evidence}</dd></div><div><dt>Blockers</dt><dd>{item.blockers}</dd></div><div><dt>Population</dt><dd>Manager-owned job or assigned candidate only</dd></div><div><dt>Decision boundary</dt><dd>No automated recommendation</dd></div></dl>{item.type === "Decision" || item.type === "Requisition" ? <><label className="checkbox-row"><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} />I reviewed the current version and required independent evidence.</label><div className="detail-action-strip"><button disabled={!confirmed || item.blockers !== "None"} className="primary-button" onClick={() => { setDecision(item.type === "Decision" ? "Advance approved" : "Requisition approved"); announce(`${item.id} human decision recorded in browser memory.`); }}>Approve current version</button><button className="secondary-button" onClick={() => { setDecision("Sent back"); announce(`${item.id} sent back with an attributed reason.`); }}>Send back</button></div></> : <button className="primary-button" onClick={() => announce(`${item.id} owned manager action completed in memory.`)}>Complete owned action</button>}</section><aside className="panel manager-privacy"><LockKeyhole size={22} /><h2>Manager boundary</h2><p>Private support, background content, peer feedback before submission, compensation outside approval scope and other jobs remain hidden.</p></aside></div></PortalShell>;
  const rows = managerRecruitingItems;
  return <PortalShell kind="manager-recruiting"><section className="role-portal-hero"><div><ScreenId>UI-MGR-002</ScreenId><span className="eyebrow">Hiring manager recruiting workspace</span><h1>Own outcomes, evidence and human decisions.</h1><p>Approve requisitions, inspect pipeline health, complete interview plans, debrief and decide within scope.</p></div><Pill tone="warning">{rows.filter((r) => r.status !== "Complete").length} active</Pill></section><section className="role-summary-cards"><article><BriefcaseBusiness size={22} /><strong>{new Set(rows.map((r) => r.job)).size}</strong><span>Jobs</span></article><article><ClipboardCheck size={22} /><strong>{rows.filter((r) => r.type === "Requisition").length}</strong><span>Requisitions</span></article><article><UsersRound size={22} /><strong>{rows.filter((r) => r.type === "Pipeline").length}</strong><span>Pipeline reviews</span></article><article><AlertTriangle size={22} /><strong>{rows.filter((r) => r.blockers !== "None").length}</strong><span>Blocked</span></article></section><section className="panel role-record-list">{rows.map((row) => <NavLink to={`/manager/recruiting/${row.id}`} key={row.id}><span className="role-portal-record-icon"><BriefcaseBusiness size={18} /></span><span><strong>{row.type}</strong><small>{row.id} · {row.job}</small></span><span><strong>{row.candidate}</strong><small>{row.evidence}</small></span><Pill tone={statusTone(row.status)}>{row.status}</Pill></NavLink>)}</section></PortalShell>;
}

function InterviewerPortal() {
  const { assignmentId } = useParams();
  const { announce } = usePrototype();
  const item = interviewerPortalItems.find((row) => row.id === assignmentId);
  const [tab, setTab] = useState("Briefing");
  const [saved, setSaved] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  if (assignmentId && !item) return <PortalShell kind="interviewer"><section className="role-access-denied"><LockKeyhole size={28} /><h1>Interview assignment unavailable</h1><p>Direct access cannot expand interviewer assignment scope.</p><NavLink className="primary-button" to="/interviewer">Return to assignments</NavLink></section></PortalShell>;
  if (item) return <PortalShell kind="interviewer"><NavLink className="back-link" to="/interviewer"><ArrowLeft size={15} /> My interviews</NavLink><section className="role-portal-hero compact"><div><ScreenId>UI-INT-001</ScreenId><span className="eyebrow">{item.id} · {item.scorecardVersion}</span><h1>{item.focus}</h1><p>{item.candidate} · {item.job} · {item.session}</p></div><Pill tone={statusTone(submitted ? "Complete" : item.status)}>{submitted ? "Submitted and locked" : item.status}</Pill></section><div className="candidate-hub-tabs" role="tablist" aria-label="Interviewer views">{["Briefing", "Question plan", "Scorecard"].map((name) => <button role="tab" aria-selected={tab === name} onClick={() => setTab(name)} key={name}>{name}</button>)}</div>{tab === "Briefing" && <section className="panel"><h2>Minimum-necessary briefing</h2><dl className="case-fact-grid"><div><dt>Focus</dt><dd>{item.focus}</dd></div><div><dt>When</dt><dd>{item.session} · {item.timezone}</dd></div><div><dt>Conflict</dt><dd>{item.conflict}</dd></div><div><dt>Excluded</dt><dd>Other feedback, compensation, background and private support</dd></div></dl><button className="secondary-button" onClick={() => announce(`${item.id} accessible résumé preview opened without other evaluation.`)}>Open approved résumé</button></section>}{tab === "Question plan" && <section className="panel"><h2>Owned structured questions</h2><ol className="task-step-list"><li><span>1</span>How did you define the user and decision?</li><li><span>2</span>What evidence changed your approach?</li><li><span>3</span>How did accessibility affect the design?</li><li><span>4</span>What would you measure after release?</li></ol><button className="secondary-button" onClick={() => announce(`${item.id} conflict and accommodation reminder acknowledged.`)}>Acknowledge briefing</button></section>}{tab === "Scorecard" && <section className="panel portal-form-page"><h2>Independent scorecard</h2>{submitted ? <div className="completion-receipt"><CheckCircle2 size={23} /><div><strong>Scorecard submitted and locked</strong><span>Peer feedback becomes visible only after submission.</span></div></div> : <form className="portal-form" onSubmit={(e) => { e.preventDefault(); setSubmitted(true); announce(`${item.id} independent scorecard submitted.`); }}><label>Evidence<textarea defaultValue="Prepared synthetic behavioral evidence with observable context and outcome." /></label><label>Assessment<select><option>Strong evidence</option><option>Evidence</option><option>Mixed evidence</option><option>Insufficient evidence</option></select></label><label className="checkbox-row"><input type="checkbox" checked={saved} onChange={(e) => setSaved(e.target.checked)} />I completed this independently and used only job-related evidence.</label><button disabled={!saved} className="primary-button" type="submit">Submit and lock scorecard</button></form>}</section>}</PortalShell>;
  return <PortalShell kind="interviewer"><section className="role-portal-hero"><div><ScreenId>UI-INT-001</ScreenId><span className="eyebrow">Interviewer portal</span><h1>Prepare clearly. Submit independently.</h1><p>See only assigned sessions, approved briefing and owned evidence.</p></div><Pill tone="info">{interviewerPortalItems.length} assignments</Pill></section><section className="panel role-record-list">{interviewerPortalItems.map((row) => <NavLink to={`/interviewer/${row.id}`} key={row.id}><span className="role-portal-record-icon"><UserCheck size={18} /></span><span><strong>{row.focus}</strong><small>{row.id} · {row.job}</small></span><span><strong>{row.session}</strong><small>{row.conflict}</small></span><Pill tone={statusTone(row.status)}>{row.status}</Pill></NavLink>)}</section></PortalShell>;
}

function BuddyPortal() {
  const { planId } = useParams();
  const { announce } = usePrototype();
  const item = buddyPlans.find((row) => row.id === planId);
  const [completed, setCompleted] = useState<string[]>([]);
  if (planId && !item) return <PortalShell kind="buddy"><section className="role-access-denied"><LockKeyhole size={28} /><h1>Buddy plan unavailable</h1><NavLink className="primary-button" to="/buddy">Return to plans</NavLink></section></PortalShell>;
  if (item) return <PortalShell kind="buddy"><NavLink className="back-link" to="/buddy"><ArrowLeft size={15} /> Buddy plans</NavLink><section className="role-portal-hero compact"><div><ScreenId>UI-BDY-001</ScreenId><span className="eyebrow">{item.id} · starts {item.start}</span><h1>{item.newHire}</h1><p>Buddy {item.buddy} · {item.location}</p></div><Pill tone={statusTone(item.status)}>{item.status}</Pill></section><div className="role-dashboard-grid"><section className="panel"><h2>Buddy commitments</h2><div className="portal-task-list">{item.goals.map((goal, index) => { const id = `${item.id}-${index}`; const done = completed.includes(id); return <article key={id}><span>{done ? <CheckCircle2 size={20} /> : <HeartHandshake size={20} />}</span><div><strong>{goal}</strong><small>Candidate-safe onboarding context only</small></div><button disabled={done} onClick={() => { setCompleted((current) => [...current, id]); announce(`${goal} completed in buddy portal memory.`); }}>{done ? "Complete" : "Mark complete"}</button></article>; })}</div></section><aside className="panel manager-privacy"><LockKeyhole size={22} /><h2>Buddy boundary</h2><p>No compensation, private forms, performance history, recruiting feedback, accommodation detail or manager-only goal notes.</p></aside></div></PortalShell>;
  return <PortalShell kind="buddy"><section className="role-portal-hero"><div><ScreenId>UI-BDY-001</ScreenId><span className="eyebrow">Buddy and mentor portal</span><h1>Make connection intentional.</h1><p>See only the starts, context and commitments assigned to this buddy relationship.</p></div><Pill tone="info">{buddyPlans.length} plans</Pill></section><section className="panel role-record-list">{buddyPlans.map((row) => <NavLink to={`/buddy/${row.id}`} key={row.id}><span className="role-portal-record-icon"><HeartHandshake size={18} /></span><span><strong>{row.newHire}</strong><small>{row.id} · starts {row.start}</small></span><span><strong>{row.buddy}</strong><small>{row.checkIns} check-ins · {row.location}</small></span><Pill tone={statusTone(row.status)}>{row.status}</Pill></NavLink>)}</section></PortalShell>;
}

function MobilityPortal() {
  const { opportunityId } = useParams();
  const location = useLocation();
  const { announce } = usePrototype();
  const item = mobilityOpportunities.find((row) => row.id === opportunityId);
  const expressing = location.pathname.endsWith("/interest");
  const [submitted, setSubmitted] = useState(false);
  const [query, setQuery] = useState("");
  if (opportunityId && !item) return <PortalShell kind="mobility"><section className="role-access-denied"><LockKeyhole size={28} /><h1>Internal opportunity unavailable</h1><NavLink className="primary-button" to="/mobility">Return to opportunities</NavLink></section></PortalShell>;
  if (item && expressing) return <PortalShell kind="mobility"><NavLink className="back-link" to={`/mobility/${item.id}`}><ArrowLeft size={15} /> Opportunity</NavLink><section className="panel portal-form-page"><ScreenId>UI-MOB-001</ScreenId><h1>Express private interest in {item.title}.</h1><p>{item.managerVisibility}. This creates a mobility consideration—not an external application.</p>{submitted ? <div className="completion-receipt"><CheckCircle2 size={23} /><div><strong>Interest MOBI-MEM-001 submitted</strong><span>Internal candidate controls when manager disclosure occurs.</span></div></div> : <form className="portal-form" onSubmit={(e) => { e.preventDefault(); setSubmitted(true); announce(`${item.id} internal interest submitted in memory.`); }}><label>Relevant experience<textarea defaultValue="Prepared synthetic internal-mobility evidence." /></label><label>Manager disclosure<select><option>Keep private until recruiter conversation</option><option>Notify manager after recruiter confirms eligibility</option><option>I have already discussed this with my manager</option></select></label><label className="checkbox-row"><input type="checkbox" required />Create a separate internal consideration using only the data previewed here.</label><button className="primary-button" type="submit">Submit private interest</button></form>}</section></PortalShell>;
  if (item) return <PortalShell kind="mobility"><NavLink className="back-link" to="/mobility"><ArrowLeft size={15} /> Opportunities</NavLink><section className="role-portal-hero compact"><div><ScreenId>UI-MOB-001</ScreenId><span className="eyebrow">{item.id} · closes {item.closing}</span><h1>{item.title}</h1><p>{item.team} · {item.location}</p></div><Pill tone={item.eligibility.startsWith("Review") ? "warning" : "success"}>{item.eligibility}</Pill></section><div className="role-dashboard-grid"><section className="panel"><h2>Opportunity and privacy</h2><dl className="case-fact-grid"><div><dt>Skills</dt><dd>{item.skills.join(" · ")}</dd></div><div><dt>Manager visibility</dt><dd>{item.managerVisibility}</dd></div><div><dt>Current state</dt><dd>{item.interestState}</dd></div><div><dt>Application model</dt><dd>Separate internal consideration</dd></div></dl><NavLink className="primary-button" to={`/mobility/${item.id}/interest`}>Express private interest</NavLink></section><aside className="panel manager-privacy"><LockKeyhole size={22} /><h2>Employee control</h2><p>Browsing and draft interest are private. Current performance or manager sentiment cannot be silently copied into the mobility review.</p></aside></div></PortalShell>;
  const rows = mobilityOpportunities.filter((row) => `${row.title} ${row.team} ${row.location}`.toLowerCase().includes(query.toLowerCase()));
  return <PortalShell kind="mobility"><section className="role-portal-hero"><div><ScreenId>UI-MOB-001</ScreenId><span className="eyebrow">Internal talent marketplace</span><h1>Explore growth without silent disclosure.</h1><p>Eligibility, privacy, data reuse and manager visibility are explicit.</p></div><Pill tone="info">{rows.length} opportunities</Pill></section><section className="panel role-record-list"><div className="table-toolbar"><label><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search roles, teams or locations" /></label></div>{rows.map((row) => <NavLink to={`/mobility/${row.id}`} key={row.id}><span className="role-portal-record-icon"><GraduationCap size={18} /></span><span><strong>{row.title}</strong><small>{row.id} · {row.team}</small></span><span><strong>{row.location}</strong><small>{row.managerVisibility}</small></span><Pill tone={row.eligibility.startsWith("Review") ? "warning" : "success"}>{row.eligibility}</Pill></NavLink>)}</section></PortalShell>;
}

export function AdditionalPortalsV3() {
  const path = useLocation().pathname;
  if (path.startsWith("/referrer")) return <ReferrerPortal />;
  if (path.startsWith("/facilities")) return <FacilitiesPortal />;
  if (path.startsWith("/manager/recruiting")) return <ManagerRecruitingPortal />;
  if (path.startsWith("/interviewer")) return <InterviewerPortal />;
  if (path.startsWith("/buddy")) return <BuddyPortal />;
  return <MobilityPortal />;
}
