import { useState } from "react";
import { NavLink, useLocation, useNavigate, useParams } from "react-router-dom";
import { AlertTriangle, ArrowLeft, Bell, CheckCircle2, Database, FileSpreadsheet, KeyRound, LockKeyhole, Plus, RefreshCcw, Search, Send, Settings2, ShieldCheck, UserCog, UsersRound } from "lucide-react";
import { adminUsers, contentTemplates, importRuns, integrationConfigs, notificationItems, type JourneyStatus } from "../data/fullSystem";
import { usePrototype } from "../prototype/PrototypeContext";
import { Pill, ScreenId } from "./Common";
import { HrShell } from "./HrWorkspace";

const accessRequests = Array.from({ length: 12 }, (_, index) => ({ id: `ACR-DEMO-${String(index + 1).padStart(3, "0")}`, person: adminUsers[index % adminUsers.length].name, role: adminUsers[index % adminUsers.length].role, scope: ["Assigned portfolio", "Country operations", "Temporary support case", "Configuration review"][index % 4], status: ["Ready", "Blocked", "Active", "Complete"][index % 4], expires: `Sep ${8 + index} · 5:00 PM`, approver: ["Data owner", "Security", "Functional owner"][index % 3] }));
const privacyOperations = Array.from({ length: 14 }, (_, index) => ({ id: `PRI-OPS-${String(index + 1).padStart(3, "0")}`, type: ["Access", "Correction", "Deletion", "Restriction", "Consent withdrawal"][index % 5], subject: `Candidate fixture ${String(index + 1).padStart(2, "0")}`, status: ["Identity check", "Scope review", "Retention review", "Execution", "Reconciliation"][index % 5], systems: 3 + index % 7, due: `Sep ${4 + index}`, owner: ["Privacy Operations", "Legal", "Data Operations"][index % 3] }));

function tone(state: string) {
  if (["Active", "Complete", "Resolved", "Healthy"].includes(state)) return "success" as const;
  if (["Blocked", "Cancelled", "Critical"].includes(state)) return "danger" as const;
  if (["Draft", "Normal"].includes(state)) return "neutral" as const;
  return "warning" as const;
}

function AdminNav() {
  return <nav className="workspace-subnav" aria-label="Administration"><NavLink end to="/admin">Overview</NavLink><NavLink to="/admin/users">Users &amp; access</NavLink><NavLink to="/admin/notifications">Notifications</NavLink><NavLink to="/admin/content">Content</NavLink><NavLink to="/admin/integrations">Integrations</NavLink><NavLink to="/admin/imports">Imports</NavLink><NavLink to="/admin/identity">Identity</NavLink><NavLink to="/admin/privacy-requests">Privacy</NavLink></nav>;
}

function AdminFrame({ title, eyebrow, id, children, actions }: { title: string; eyebrow: string; id: string; children: React.ReactNode; actions?: React.ReactNode }) {
  return <HrShell title={title} eyebrow={eyebrow} screenId={id} screen="platform" actions={actions}><AdminNav />{children}</HrShell>;
}

function AdminOverview() {
  const cards = [
    ["Users", adminUsers.length, "/admin/users", UserCog],
    ["Access requests", accessRequests.length, "/admin/access-requests", ShieldCheck],
    ["Unread notifications", notificationItems.filter((row) => !row.read).length, "/admin/notifications", Bell],
    ["Content versions", contentTemplates.length, "/admin/content", Send],
    ["Integration queues", integrationConfigs.reduce((sum, row) => sum + row.queue, 0), "/admin/integrations", RefreshCcw],
    ["Import runs", importRuns.length, "/admin/imports", FileSpreadsheet],
    ["Identity controls", 6, "/admin/identity", KeyRound],
    ["Privacy operations", privacyOperations.length, "/admin/privacy-requests", LockKeyhole],
  ] as const;
  return <AdminFrame title="Administration and platform control" eyebrow="Identity, access, content, integrations and data movement" id="UI-ADM-001"><section className="admin-overview-grid">{cards.map(([label, count, to, Icon]) => <NavLink key={label} to={to}><Icon size={24} /><span><strong>{count}</strong><small>{label}</small></span><em>Open workspace</em></NavLink>)}</section><div className="system-detail-grid"><section className="panel"><h2>Control posture</h2><dl className="case-fact-grid"><div><dt>Authentication</dt><dd>SSO + MFA wireframe states</dd></div><div><dt>Authorization</dt><dd>Persona, row and field boundary previews</dd></div><div><dt>Audit</dt><dd>Actor, action, version, reason and receipt</dd></div><div><dt>Persistence</dt><dd>Browser memory only</dd></div></dl></section><aside className="panel recovery-panel"><AlertTriangle size={23} /><h2>Production boundary</h2><p>No identity provider, credential, API, database, file transfer or external system is connected. These are complete interaction contracts for a future implementation.</p></aside></div></AdminFrame>;
}

function UserAccessOperations() {
  const { userId, requestId } = useParams();
  const location = useLocation();
  const { announce } = usePrototype();
  const user = adminUsers.find((row) => row.id === userId);
  const request = accessRequests.find((row) => row.id === requestId);
  const creating = location.pathname.endsWith("/new");
  const editing = location.pathname.endsWith("/edit");
  const isRequest = location.pathname.startsWith("/admin/access-requests");
  const [saved, setSaved] = useState(false);
  const [state, setState] = useState<JourneyStatus>(user?.status ?? "Draft");
  const [query, setQuery] = useState("");
  if (isRequest && requestId && !request) return <AdminFrame title="Access request unavailable" eyebrow={requestId} id="UI-ADM-002"><section className="panel empty-state"><ShieldCheck size={28} /><h2>Request not found</h2><NavLink className="primary-button" to="/admin/access-requests">Return to requests</NavLink></section></AdminFrame>;
  if (isRequest && request) return <AdminFrame title={`${request.person} access request`} eyebrow={`${request.id} · ${request.role}`} id="UI-ADM-002"><div className="system-detail-grid"><section className="panel record-detail-page"><div className="panel-heading"><h2>{request.scope}</h2><Pill tone={tone(request.status)}>{request.status}</Pill></div><dl className="case-fact-grid"><div><dt>Role</dt><dd>{request.role}</dd></div><div><dt>Scope</dt><dd>{request.scope}</dd></div><div><dt>Expiry</dt><dd>{request.expires}</dd></div><div><dt>Approver</dt><dd>{request.approver}</dd></div></dl><label className="checkbox-row"><input type="checkbox" required />I verified purpose, owner, scope, segregation and expiry.</label><div className="detail-action-strip"><button className="primary-button" onClick={() => announce(`${request.id} approved with effective-dated scope in memory.`)}>Approve bounded access</button><button className="secondary-button" onClick={() => announce(`${request.id} sent back for narrower scope.`)}>Request changes</button><button className="danger-button" onClick={() => announce(`${request.id} denied with reason and audit receipt.`)}>Deny request</button></div></section><aside className="panel recovery-panel"><ShieldCheck size={22} /><h2>Destination check</h2><p>Approval creates no access until identity, role, scope, effective time and destination reconciliation all agree.</p></aside></div></AdminFrame>;
  if (isRequest) return <AdminFrame title="Access request queue" eyebrow="Purpose, owner, scope, expiry and approval" id="UI-ADM-002"><section className="panel role-record-list">{accessRequests.map((row) => <NavLink key={row.id} to={`/admin/access-requests/${row.id}`}><ShieldCheck size={19} /><span><strong>{row.person}</strong><small>{row.id} · {row.role}</small></span><span><strong>{row.scope}</strong><small>Expires {row.expires}</small></span><Pill tone={tone(row.status)}>{row.status}</Pill></NavLink>)}</section></AdminFrame>;
  if (userId && !user && !creating) return <AdminFrame title="User unavailable" eyebrow={userId} id="UI-ADM-002"><section className="panel empty-state"><UserCog size={28} /><h2>User not found</h2><NavLink className="primary-button" to="/admin/users">Return to users</NavLink></section></AdminFrame>;
  if (creating || editing) return <AdminFrame title={creating ? "Create platform user" : `Edit ${user?.name}`} eyebrow="Identity-bound access configuration" id="UI-ADM-002"><section className="panel admin-form-page"><NavLink className="back-link" to={user ? `/admin/users/${user.id}` : "/admin/users"}><ArrowLeft size={15} /> Users</NavLink>{saved ? <div className="completion-receipt"><CheckCircle2 size={23} /><div><strong>{creating ? "User USR-MEM-001 prepared" : "User access version saved"}</strong><span>Provisioning and destination reconciliation remain separate.</span></div></div> : <form className="portal-form" onSubmit={(event) => { event.preventDefault(); setSaved(true); announce("Platform user draft saved in browser memory."); }}><div className="form-grid"><label>Person fixture<input defaultValue={user?.name ?? "Taylor Morgan"} /></label><label>Role<select defaultValue={user?.role ?? "Recruiter"}>{[...new Set(adminUsers.map((row) => row.role))].map((role) => <option key={role}>{role}</option>)}</select></label><label>Scope<input defaultValue={user?.scope ?? "Assigned portfolio"} /></label><label>Effective through<input type="datetime-local" defaultValue="2026-09-15T17:00" /></label><label>MFA<select defaultValue={user?.mfa ?? "Enforced · verified"}><option>Enforced · verified</option><option>Enrollment required</option><option>Recovery required</option></select></label><label>Delegation<select><option>Not delegated</option><option>Temporary owner-approved delegation</option></select></label><label className="full">Business reason<textarea defaultValue="Prepared synthetic access reason." /></label><label className="full checkbox-row"><input type="checkbox" required />Create an access request before any destination provisioning.</label></div><button className="primary-button" type="submit">Save user access draft</button></form>}</section></AdminFrame>;
  if (user) return <AdminFrame title={user.name} eyebrow={`${user.id} · ${user.role}`} id="UI-ADM-002" actions={<NavLink className="secondary-button" to={`/admin/users/${user.id}/edit`}>Edit access</NavLink>}><div className="system-detail-grid"><section className="panel record-detail-page"><div className="panel-heading"><h2>{user.scope}</h2><Pill tone={tone(state)}>{state}</Pill></div><dl className="case-fact-grid"><div><dt>MFA</dt><dd>{user.mfa}</dd></div><div><dt>Last access</dt><dd>{user.lastAccess}</dd></div><div><dt>Temporary until</dt><dd>{user.temporaryUntil}</dd></div><div><dt>Session policy</dt><dd>30-minute inactivity · re-auth for restricted data</dd></div></dl><div className="detail-action-strip"><button className="secondary-button" onClick={() => announce(`${user.id} access-review evidence opened.`)}>Review effective access</button><button className="danger-button" onClick={() => { setState("Cancelled"); announce(`${user.id} revoked with destination reconciliation preview.`); }}>Revoke access</button></div></section><aside className="panel recovery-panel"><AlertTriangle size={22} /><h2>Recovery</h2><p>Orphaned roles, identity mismatch, failed deprovisioning and stale sessions create owned recovery work.</p></aside></div></AdminFrame>;
  const rows = adminUsers.filter((row) => `${row.name} ${row.role} ${row.id}`.toLowerCase().includes(query.toLowerCase()));
  return <AdminFrame title="Users and effective access" eyebrow="Identity, role, scope, MFA, delegation and expiry" id="UI-ADM-002" actions={<><NavLink className="secondary-button" to="/admin/access-requests">Access requests</NavLink><NavLink className="primary-button" to="/admin/users/new"><Plus size={15} /> New user</NavLink></>}><section className="panel role-record-list"><div className="table-toolbar"><label><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search user, role or ID" /></label><Pill tone="info">{rows.length} users</Pill></div>{rows.map((row) => <NavLink key={row.id} to={`/admin/users/${row.id}`}><UserCog size={19} /><span><strong>{row.name}</strong><small>{row.id} · {row.role}</small></span><span><strong>{row.scope}</strong><small>{row.mfa}</small></span><Pill tone={tone(row.status)}>{row.status}</Pill></NavLink>)}</section></AdminFrame>;
}

function NotificationOperations() {
  const { notificationId } = useParams();
  const navigate = useNavigate();
  const item = notificationItems.find((row) => row.id === notificationId);
  const [read, setRead] = useState<string[]>(notificationItems.filter((row) => row.read).map((row) => row.id));
  if (notificationId && !item) return <AdminFrame title="Notification unavailable" eyebrow={notificationId} id="UI-ADM-003"><section className="panel empty-state"><Bell size={28} /><h2>Notification not found</h2><NavLink className="primary-button" to="/admin/notifications">Return to notifications</NavLink></section></AdminFrame>;
  if (item) return <AdminFrame title={item.title} eyebrow={`${item.id} · ${item.category}`} id="UI-ADM-003"><div className="system-detail-grid"><section className="panel record-detail-page"><div className="panel-heading"><h2>Due {item.due}</h2><Pill tone={tone(item.priority)}>{item.priority}</Pill></div><p>{item.context}</p><dl className="case-fact-grid"><div><dt>Category</dt><dd>{item.category}</dd></div><div><dt>Read state</dt><dd>{read.includes(item.id) ? "Read" : "Unread"}</dd></div><div><dt>Deep link</dt><dd>{item.target}</dd></div><div><dt>Delivery</dt><dd>In-app fixture · no external message</dd></div></dl><div className="detail-action-strip"><button className="secondary-button" onClick={() => setRead((current) => current.includes(item.id) ? current : [...current, item.id])}>Mark read</button><button className="primary-button" onClick={() => navigate(item.target)}>Open authorized destination</button></div></section><aside className="panel"><ShieldCheck size={22} /><h2>Least disclosure</h2><p>The notification carries only enough context to act. Row and field access are rechecked after the deep link opens.</p></aside></div></AdminFrame>;
  return <AdminFrame title="Notification center" eyebrow="Owned, actionable, deep-linked work" id="UI-ADM-003"><section className="panel role-record-list">{notificationItems.map((row) => <NavLink key={row.id} to={`/admin/notifications/${row.id}`} className={read.includes(row.id) ? "is-read" : ""}><Bell size={19} /><span><strong>{row.title}</strong><small>{row.id} · {row.category}</small></span><span><strong>Due {row.due}</strong><small>{row.context}</small></span><Pill tone={tone(row.priority)}>{row.priority}</Pill></NavLink>)}</section></AdminFrame>;
}

function ContentOperations() {
  const { contentId } = useParams();
  const location = useLocation();
  const { announce } = usePrototype();
  const item = contentTemplates.find((row) => row.id === contentId);
  const creating = location.pathname.endsWith("/new");
  const editing = location.pathname.endsWith("/edit");
  const [saved, setSaved] = useState(false);
  const [approved, setApproved] = useState(false);
  const [query, setQuery] = useState("");
  if (contentId && !item && !creating) return <AdminFrame title="Content unavailable" eyebrow={contentId} id="UI-ADM-004"><section className="panel empty-state"><Send size={28} /><h2>Content version not found</h2><NavLink className="primary-button" to="/admin/content">Return to content</NavLink></section></AdminFrame>;
  if (creating || editing) return <AdminFrame title={creating ? "Create content template" : `Edit ${item?.name}`} eyebrow="Versioned, localized communication" id="UI-ADM-004"><section className="panel admin-form-page"><NavLink className="back-link" to={item ? `/admin/content/${item.id}` : "/admin/content"}><ArrowLeft size={15} /> Content</NavLink>{saved ? <div className="completion-receipt"><CheckCircle2 size={23} /><div><strong>Draft content version saved</strong><span>Preview, variables and approval remain required before activation.</span></div></div> : <form className="portal-form" onSubmit={(event) => { event.preventDefault(); setSaved(true); announce("Content template draft saved in memory."); }}><div className="form-grid"><label>Name<input defaultValue={item?.name ?? "Application next step"} /></label><label>Channel<select defaultValue={item?.channel ?? "Email"}><option>Email</option><option>Portal</option><option>SMS</option><option>Accessible document</option></select></label><label>Locale<input defaultValue={item?.locale ?? "en-US"} /></label><label>Audience<select defaultValue={item?.audience ?? "Candidate"}><option>Candidate</option><option>New hire</option><option>Manager</option><option>Agency</option></select></label><label className="full">Subject<input defaultValue="{{job_title}} update" /></label><label className="full">Accessible body<textarea defaultValue="Hello {{recipient_name}}, this prepared content uses a version-bound support route: {{support_route}}." /></label><label className="full">Variables<input defaultValue={(item?.variables ?? ["recipient_name", "job_title", "support_route"]).join(", ")} /></label></div><button className="primary-button" type="submit">Save draft version</button></form>}</section></AdminFrame>;
  if (item) return <AdminFrame title={item.name} eyebrow={`${item.id} · v${item.version} · ${item.locale}`} id="UI-ADM-004" actions={<NavLink className="secondary-button" to={`/admin/content/${item.id}/edit`}>Edit new version</NavLink>}><div className="system-detail-grid"><section className="panel record-detail-page"><div className="panel-heading"><h2>{item.channel} · {item.audience}</h2><Pill tone={tone(approved ? "Active" : item.status)}>{approved ? "Active demo" : item.status}</Pill></div><div className="locale-preview"><span className="eyebrow">Candidate-safe preview</span><h2>{item.name}</h2><p>Hello Maya, this is the approved {item.locale} preview with local datetime, job title and private support route.</p></div><dl className="case-fact-grid"><div><dt>Effective</dt><dd>{item.effective}</dd></div><div><dt>Owner</dt><dd>{item.owner}</dd></div><div><dt>Variables</dt><dd>{item.variables.join(" · ")}</dd></div><div><dt>Fallback</dt><dd>Block when required locale/version is unavailable</dd></div></dl><div className="detail-action-strip"><button className="secondary-button" onClick={() => announce(`${item.id} variable, broken-link and accessible-render validation passed.`)}>Run preview validation</button><button className="primary-button" onClick={() => { setApproved(true); announce(`${item.id} synthetic content version activated in memory.`); }}>Approve and activate demo</button></div></section><aside className="panel recovery-panel"><AlertTriangle size={22} /><h2>Delivery recovery</h2><p>Bounce, stale version, missing locale, bad variable or withdrawn authority retains the last safe communication state.</p></aside></div></AdminFrame>;
  const rows = contentTemplates.filter((row) => `${row.name} ${row.locale} ${row.channel}`.toLowerCase().includes(query.toLowerCase()));
  return <AdminFrame title="Content and communication templates" eyebrow="Version, locale, channel, variables and approval" id="UI-ADM-004" actions={<NavLink className="primary-button" to="/admin/content/new"><Plus size={15} /> New template</NavLink>}><section className="panel role-record-list"><div className="table-toolbar"><label><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search content or locale" /></label><Pill tone="info">{rows.length} versions</Pill></div>{rows.map((row) => <NavLink key={row.id} to={`/admin/content/${row.id}`}><Send size={19} /><span><strong>{row.name}</strong><small>{row.id} · {row.locale} · v{row.version}</small></span><span><strong>{row.channel}</strong><small>{row.audience} · {row.owner}</small></span><Pill tone={tone(row.status)}>{row.status}</Pill></NavLink>)}</section></AdminFrame>;
}

function IntegrationOperations() {
  const { integrationId } = useParams();
  const location = useLocation();
  const { announce } = usePrototype();
  const item = integrationConfigs.find((row) => row.id === integrationId);
  const mapping = location.pathname.endsWith("/mapping");
  const credentials = location.pathname.endsWith("/credentials");
  const [tested, setTested] = useState(false);
  const [saved, setSaved] = useState(false);
  if (integrationId && !item) return <AdminFrame title="Integration unavailable" eyebrow={integrationId} id="UI-ADM-005"><section className="panel empty-state"><Database size={28} /><h2>Integration configuration not found</h2><NavLink className="primary-button" to="/admin/integrations">Return to integrations</NavLink></section></AdminFrame>;
  if (item && (mapping || credentials)) return <AdminFrame title={`${item.name} · ${mapping ? "field mapping" : "credential rotation"}`} eyebrow={`${item.id} · ${item.mappingVersion}`} id="UI-ADM-005"><section className="panel admin-form-page"><NavLink className="back-link" to={`/admin/integrations/${item.id}`}><ArrowLeft size={15} /> Integration</NavLink>{saved ? <div className="completion-receipt"><CheckCircle2 size={23} /><div><strong>{mapping ? "Mapping draft saved" : "Synthetic credential rotation prepared"}</strong><span>Activation, secret storage and provider handshake are not performed.</span></div></div> : <form className="portal-form" onSubmit={(event) => { event.preventDefault(); setSaved(true); announce(`${item.id} ${mapping ? "mapping" : "credential"} draft saved in memory.`); }}>{mapping ? <div className="mapping-grid"><strong>Source field</strong><strong>Destination field</strong><strong>Rule</strong>{["business_key", "effective_date", "status", "owner_id", "locale"].map((field) => <span key={field}><input defaultValue={field} /><input defaultValue={`target_${field}`} /><select><option>Copy when present</option><option>Normalize</option><option>Reject when missing</option></select></span>)}</div> : <div className="form-grid"><label>Credential alias<input defaultValue={`${item.id}-PRIMARY`} /></label><label>Rotation window<input type="datetime-local" defaultValue="2026-09-04T18:00" /></label><label>Authentication<select><option>OAuth client credentials</option><option>Signed webhook</option><option>mTLS</option></select></label><label>Secret<input type="password" value="synthetic-secret-not-stored" readOnly /></label><label className="full checkbox-row"><input type="checkbox" required />Use a managed secret store and overlap old/new credentials until reconciliation.</label></div>}<button className="primary-button" type="submit">Save inactive draft</button></form>}</section></AdminFrame>;
  if (item) return <AdminFrame title={item.name} eyebrow={`${item.id} · ${item.provider}`} id="UI-ADM-005" actions={<><NavLink className="secondary-button" to={`/admin/integrations/${item.id}/mapping`}>Field mapping</NavLink><NavLink className="secondary-button" to={`/admin/integrations/${item.id}/credentials`}>Credentials</NavLink></>}><div className="system-detail-grid"><section className="panel record-detail-page"><div className="panel-heading"><h2>{item.direction}</h2><Pill tone={tone(item.status)}>{item.status}</Pill></div><dl className="case-fact-grid"><div><dt>Authentication</dt><dd>{item.authState}</dd></div><div><dt>Mapping</dt><dd>{item.mappingVersion}</dd></div><div><dt>Queue</dt><dd>{item.queue}</dd></div><div><dt>Reconciled</dt><dd>{item.lastReconciled}</dd></div><div><dt>Failure</dt><dd>{item.failure}</dd></div><div><dt>Business key</dt><dd>Stable source ID + destination receipt</dd></div></dl><div className="detail-action-strip"><button className="secondary-button" onClick={() => { setTested(true); announce(`${item.id} synthetic connection and schema test completed.`); }}>{tested ? "Test passed" : "Test configuration"}</button><button className="primary-button" onClick={() => announce(`${item.id} reconciliation preview opened with queue, duplicates and unmatched receipts.`)}>Open reconciliation</button></div></section><aside className="panel recovery-panel"><RefreshCcw size={22} /><h2>Replay contract</h2><p>Every retry uses the same business key, checks destination state, preserves the last safe source state and produces a reconciled receipt.</p></aside></div></AdminFrame>;
  return <AdminFrame title="Integration control plane" eyebrow="Configuration, mapping, credentials, queue and recovery" id="UI-ADM-005"><section className="panel role-record-list">{integrationConfigs.map((row) => <NavLink key={row.id} to={`/admin/integrations/${row.id}`}><Database size={19} /><span><strong>{row.name}</strong><small>{row.id} · {row.provider}</small></span><span><strong>{row.mappingVersion}</strong><small>{row.queue} queued · {row.lastReconciled}</small></span><Pill tone={tone(row.status)}>{row.status}</Pill></NavLink>)}</section></AdminFrame>;
}

function ImportOperations() {
  const { importId } = useParams();
  const location = useLocation();
  const { announce } = usePrototype();
  const item = importRuns.find((row) => row.id === importId);
  const creating = location.pathname.endsWith("/new");
  const validating = location.pathname.endsWith("/validate");
  const correcting = location.pathname.endsWith("/correct");
  const [saved, setSaved] = useState(false);
  const [validated, setValidated] = useState(false);
  if (importId && !item) return <AdminFrame title="Import unavailable" eyebrow={importId} id="UI-ADM-006"><section className="panel empty-state"><FileSpreadsheet size={28} /><h2>Import run not found</h2><NavLink className="primary-button" to="/admin/imports">Return to imports</NavLink></section></AdminFrame>;
  if (creating) return <AdminFrame title="Create governed import" eyebrow="Type, file contract, dry run and rollback" id="UI-ADM-006"><section className="panel admin-form-page">{saved ? <div className="completion-receipt"><CheckCircle2 size={23} /><div><strong>Import IMP-MEM-001 staged</strong><span>No file was uploaded or record written.</span></div></div> : <form className="portal-form" onSubmit={(event) => { event.preventDefault(); setSaved(true); announce("Synthetic import staged in browser memory."); }}><div className="form-grid"><label>Object type<select><option>Jobs</option><option>Candidates</option><option>Applications</option><option>Agencies</option><option>Onboarding plans</option></select></label><label>Fixture file<select><option>synthetic-v3-fixture.csv</option><option>synthetic-correction-fixture.csv</option></select></label><label>Duplicate key<select><option>External ID + source</option><option>Email hash + tenant</option></select></label><label>Mode<select><option>Dry run only</option><option>Prepared commit preview</option></select></label><label className="full checkbox-row"><input type="checkbox" required />Generate row validation, warnings, inverse plan and reconciliation report before commit.</label></div><button className="primary-button" type="submit">Stage dry run</button></form>}</section></AdminFrame>;
  if (item && (validating || correcting)) return <AdminFrame title={`${validating ? "Validate" : "Correct"} ${item.id}`} eyebrow={`${item.file} · ${item.type}`} id="UI-ADM-006"><div className="system-detail-grid"><section className="panel"><h2>Row-level preview</h2><div className="import-error-grid">{Array.from({ length: 12 }, (_, index) => <article key={index}><span>Row {4 + index * 9}</span><strong>{index % 3 === 0 ? "Missing business key" : index % 3 === 1 ? "Unknown locale" : "Duplicate relationship"}</strong><select aria-label={`Resolution for row ${4 + index * 9}`}><option>Exclude row</option><option>Map prepared value</option><option>Merge by business key</option></select></article>)}</div><button className="primary-button" onClick={() => { setValidated(true); announce(`${item.id} corrected rows revalidated in memory.`); }}>{validated ? "Validation passed for prepared corrections" : "Revalidate prepared corrections"}</button></section><aside className="panel recovery-panel"><ShieldCheck size={22} /><h2>Rollback contract</h2><p>{item.rollback}. No import may overwrite a governed current version without an explicit merge rule.</p></aside></div></AdminFrame>;
  if (item) return <AdminFrame title={`${item.type} import`} eyebrow={`${item.id} · ${item.file}`} id="UI-ADM-006"><section className="onboarding-metrics"><article><FileSpreadsheet size={19} /><span><strong>{item.rows}</strong>Rows</span></article><article><CheckCircle2 size={19} /><span><strong>{item.valid}</strong>Valid</span></article><article><AlertTriangle size={19} /><span><strong>{item.warnings}</strong>Warnings</span></article><article><AlertTriangle size={19} /><span><strong>{item.errors}</strong>Errors</span></article></section><div className="system-detail-grid"><section className="panel record-detail-page"><div className="panel-heading"><h2>{item.owner}</h2><Pill tone={tone(item.status)}>{item.status}</Pill></div><p>{item.rollback}</p><div className="detail-action-strip"><NavLink className="secondary-button" to={`/admin/imports/${item.id}/validate`}>Validate rows</NavLink><NavLink className="primary-button" to={`/admin/imports/${item.id}/correct`}>Correct exceptions</NavLink><button disabled={item.errors > 0} className="primary-button" onClick={() => announce(`${item.id} commit preview created with batch receipt.`)}>Commit prepared batch</button></div></section><aside className="panel recovery-panel"><RefreshCcw size={22} /><h2>Partial failure</h2><p>Batch, row, business key, prior value, new value and destination receipt support targeted rollback and replay.</p></aside></div></AdminFrame>;
  return <AdminFrame title="Governed imports" eyebrow="Validate, correct, commit, reconcile and roll back" id="UI-ADM-006" actions={<NavLink className="primary-button" to="/admin/imports/new"><Plus size={15} /> New import</NavLink>}><section className="panel role-record-list">{importRuns.map((row) => <NavLink key={row.id} to={`/admin/imports/${row.id}`}><FileSpreadsheet size={19} /><span><strong>{row.type}</strong><small>{row.id} · {row.file}</small></span><span><strong>{row.valid}/{row.rows} valid</strong><small>{row.warnings} warnings · {row.errors} errors</small></span><Pill tone={tone(row.status)}>{row.status}</Pill></NavLink>)}</section></AdminFrame>;
}

function IdentityOperations() {
  const { announce } = usePrototype();
  const [tab, setTab] = useState("SSO");
  const [saved, setSaved] = useState(false);
  const controls: Record<string, string[]> = { SSO: ["Tenant discovery", "Signed assertion", "Just-in-time creation disabled", "Break-glass route"], MFA: ["Enrollment", "Step-up for restricted data", "Recovery", "Device reset"], Sessions: ["30-minute inactivity", "Absolute lifetime", "Concurrent-session policy", "Forced revocation"], Delegation: ["Owner approval", "Purpose", "Effective dates", "No onward delegation"], "Temporary access": ["Ticket binding", "Narrow scope", "Auto expiry", "Destination revoke receipt"], "Break glass": ["Named emergency", "Dual approval", "Live alert", "Post-use review"] };
  return <AdminFrame title="Identity and session policy" eyebrow="SSO, MFA, recovery, delegation and emergency access" id="UI-ADM-007"><div className="candidate-hub-tabs" role="tablist" aria-label="Identity controls">{Object.keys(controls).map((name) => <button key={name} role="tab" aria-selected={tab === name} onClick={() => { setTab(name); setSaved(false); }}>{name}</button>)}</div><div className="system-detail-grid"><section className="panel portal-form-page"><h2>{tab} policy preview</h2><div className="evidence-checklist">{controls[tab].map((control) => <label key={control}><input type="checkbox" defaultChecked />{control}</label>)}</div><label>Failure behavior<select><option>Deny safely and open recovery</option><option>Keep existing least-privilege session</option><option>Require human security review</option></select></label><label>Policy reason<textarea defaultValue="Prepared synthetic identity-policy rationale." /></label><button className="primary-button" onClick={() => { setSaved(true); announce(`${tab} policy draft saved in browser memory.`); }}>{saved ? "Draft policy saved" : "Save inactive policy draft"}</button></section><aside className="panel recovery-panel"><KeyRound size={23} /><h2>Identity invariant</h2><p>A failed authentication, role change or revocation never expands access. Stale sessions and orphaned destination access remain visible until reconciled.</p></aside></div></AdminFrame>;
}

function PrivacyOperations() {
  const { requestId } = useParams();
  const { announce } = usePrototype();
  const item = privacyOperations.find((row) => row.id === requestId);
  const [completed, setCompleted] = useState<string[]>([]);
  if (requestId && !item) return <AdminFrame title="Privacy request unavailable" eyebrow={requestId} id="UI-ADM-008"><section className="panel empty-state"><LockKeyhole size={28} /><h2>Request not found</h2><NavLink className="primary-button" to="/admin/privacy-requests">Return to privacy operations</NavLink></section></AdminFrame>;
  if (item) { const steps = ["Verify identity", "Resolve legal hold and retention", "Collect in-scope systems", "Execute or correct", "Reconcile every destination", "Issue candidate-safe response"]; return <AdminFrame title={`${item.type} request`} eyebrow={`${item.id} · ${item.subject}`} id="UI-ADM-008"><div className="system-detail-grid"><section className="panel"><div className="panel-heading"><h2>{item.status}</h2><Pill tone="warning">Due {item.due}</Pill></div><ol className="task-step-list">{steps.map((step, index) => <li key={step}><span>{index + 1}</span><label><input type="checkbox" checked={completed.includes(step)} onChange={() => setCompleted((current) => current.includes(step) ? current.filter((x) => x !== step) : [...current, step])} />{step}</label></li>)}</ol><button disabled={completed.length !== steps.length} className="primary-button" onClick={() => announce(`${item.id} synthetic privacy execution reconciled across ${item.systems} systems.`)}>Complete with reconciliation receipt</button></section><aside className="panel recovery-panel"><ShieldCheck size={22} /><h2>{item.systems} systems in scope</h2><p>Unsupported deletion, legal hold, identity mismatch and external failure remain explicit exceptions; the system never claims completion prematurely.</p></aside></div></AdminFrame>; }
  return <AdminFrame title="Privacy request operations" eyebrow="Identity, scope, retention, execution and reconciliation" id="UI-ADM-008"><section className="panel role-record-list">{privacyOperations.map((row) => <NavLink key={row.id} to={`/admin/privacy-requests/${row.id}`}><LockKeyhole size={19} /><span><strong>{row.type}</strong><small>{row.id} · {row.subject}</small></span><span><strong>{row.status}</strong><small>{row.systems} systems · {row.owner}</small></span><Pill tone="warning">Due {row.due}</Pill></NavLink>)}</section></AdminFrame>;
}

export function AdminOperationsV3() {
  const path = useLocation().pathname;
  if (path === "/admin") return <AdminOverview />;
  if (path.startsWith("/admin/users") || path.startsWith("/admin/access-requests")) return <UserAccessOperations />;
  if (path.startsWith("/admin/notifications")) return <NotificationOperations />;
  if (path.startsWith("/admin/content")) return <ContentOperations />;
  if (path.startsWith("/admin/integrations")) return <IntegrationOperations />;
  if (path.startsWith("/admin/imports")) return <ImportOperations />;
  if (path.startsWith("/admin/identity")) return <IdentityOperations />;
  return <PrivacyOperations />;
}
