import { useState, type FormEvent } from "react";
import { NavLink, useLocation, useNavigate, useParams } from "react-router-dom";
import { AlertTriangle, ArrowLeft, Bell, CalendarDays, CheckCircle2, CircleHelp, Clock3, FileCheck2, KeyRound, LockKeyhole, Mail, MessageCircleQuestion, RefreshCcw, Save, ShieldCheck, TicketCheck, UserRoundCheck } from "lucide-react";
import { candidateTasks, jobAlerts } from "../data/lifecycleDepth";
import { careerEvents } from "../data/talentGrowth";
import { candidateTaskDetails } from "../data/fullSystem";
import { usePrototype } from "../prototype/PrototypeContext";
import { CandidateShell } from "./CandidatePortal";
import { Pill, ScreenId } from "./Common";

const supportCases = [
  { id: "SUP-DEMO-001", topic: "Assessment accessibility", status: "Open", updated: "Today · 10:14 AM", owner: "Candidate Support", next: "Support specialist response" },
  { id: "SUP-DEMO-002", topic: "Interview technology check", status: "Resolved", updated: "Aug 27 · 3:42 PM", owner: "Candidate Support", next: "No action" },
  { id: "SUP-DEMO-003", topic: "Application correction", status: "Waiting for you", updated: "Aug 26 · 11:08 AM", owner: "Application Integrity", next: "Review prepared correction" },
];

const privacyCases = [
  { id: "PRI-DEMO-001", type: "Access copy", status: "Identity verification", due: "Sep 12", scope: "Candidate profile and application history", next: "Complete identity check" },
  { id: "PRI-DEMO-002", type: "Correction", status: "In review", due: "Sep 5", scope: "Preferred name and location", next: "Privacy reviewer decision" },
  { id: "PRI-DEMO-003", type: "Deletion", status: "Retention review", due: "Sep 18", scope: "Candidate relationship", next: "Apply legal-hold and retention rules" },
];

function CandidateAccess() {
  const location = useLocation();
  const navigate = useNavigate();
  const { announce } = usePrototype();
  const [sent, setSent] = useState(false);
  const [confirmed, setConfirmed] = useState(false);
  const [verified, setVerified] = useState(false);
  const [recoveryStarted, setRecoveryStarted] = useState(false);
  const expired = location.pathname.endsWith("/expired");
  const magic = location.pathname.endsWith("/magic-link");
  const recovery = location.pathname.endsWith("/account-recovery");
  if (recovery) return <CandidateShell><section className="candidate-page access-flow"><div className="access-card"><ScreenId>UI-CAN-007</ScreenId><KeyRound size={32} /><span className="eyebrow">Account recovery</span><h1>Recover access without exposing an application.</h1><p>Recovery verifies the candidate relationship before showing any status, document or task.</p>{recoveryStarted ? <div className="completion-receipt"><CheckCircle2 size={22} /><div><strong>Recovery case REC-MEM-001 opened</strong><span>Candidate-safe verification steps are shown in this browser only.</span></div></div> : <form onSubmit={(event) => { event.preventDefault(); setRecoveryStarted(true); announce("Candidate access recovery opened in browser memory."); }}><label>Email fixture<input type="email" defaultValue="maya.chen@example.test" /></label><label>Recovery reason<select><option>Magic link expired</option><option>Email access changed</option><option>Account may be compromised</option><option>Accessibility support</option></select></label><button className="primary-button" type="submit">Start secure recovery</button></form>}<NavLink to="/sign-in">Return to sign in</NavLink></div></section></CandidateShell>;
  if (expired) return <CandidateShell><section className="candidate-page access-flow"><div className="access-card"><ScreenId>UI-CAN-007</ScreenId><AlertTriangle size={32} /><span className="eyebrow">Expired or already used link</span><h1>This sign-in link is no longer active.</h1><p>No application or account information was displayed. Request a new single-use link or use account recovery.</p><div className="candidate-control-grid"><button className="primary-button" onClick={() => { setSent(true); announce("Replacement single-use sign-in link prepared in memory."); }}>{sent ? "Replacement link prepared" : "Request another link"}</button><NavLink className="secondary-button" to="/account-recovery">Recover access</NavLink></div></div></section></CandidateShell>;
  if (magic) return <CandidateShell><section className="candidate-page access-flow"><div className="access-card"><ScreenId>UI-CAN-007</ScreenId><Mail size={32} /><span className="eyebrow">Single-use link verification</span><h1>Confirm this synthetic sign-in.</h1><dl className="offer-facts"><div><dt>Account</dt><dd>m•••@example.test</dd></div><div><dt>Issued</dt><dd>Just now</dd></div><div><dt>Expires</dt><dd>15 minutes</dd></div><div><dt>Device</dt><dd>This browser · synthetic</dd></div></dl>{verified ? <div className="completion-receipt"><CheckCircle2 size={22} /><div><strong>Identity fixture verified</strong><span>Session expires after 30 minutes of inactivity.</span></div><NavLink className="primary-button" to="/my-applications">Continue to candidate hub</NavLink></div> : <><label className="confirm-check"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />This is my synthetic sign-in request.</label><button disabled={!confirmed} className="primary-button" onClick={() => { setVerified(true); announce("Synthetic candidate identity verified for this browser session."); }}>Verify sign-in</button></>}</div></section></CandidateShell>;
  return <CandidateShell><section className="candidate-page access-flow"><div className="access-card"><ScreenId>UI-CAN-007</ScreenId><LockKeyhole size={32} /><span className="eyebrow">Candidate account</span><h1>Sign in without a password.</h1><p>Use the prepared fictional email. A real system would issue a single-use, short-lived link and recheck access at every record.</p>{sent ? <div className="completion-receipt"><CheckCircle2 size={22} /><div><strong>Check the synthetic inbox</strong><span>MAGIC-MEM-001 · expires in 15 minutes</span></div><NavLink className="primary-button" to="/sign-in/magic-link">Open prepared magic link</NavLink></div> : <form onSubmit={(event) => { event.preventDefault(); setSent(true); announce("Synthetic magic link prepared. No email was sent."); }}><label>Email<input type="email" defaultValue="maya.chen@example.test" required /></label><button className="primary-button" type="submit">Send secure sign-in link</button></form>}<div className="access-links"><NavLink to="/sign-in/expired">Preview expired link</NavLink><NavLink to="/account-recovery">I cannot access this email</NavLink></div></div></section></CandidateShell>;
}

function AlertWorkspace() {
  const { alertId } = useParams();
  const location = useLocation();
  const navigate = useNavigate();
  const { announce } = usePrototype();
  const editing = location.pathname.endsWith("/edit");
  const creating = location.pathname.endsWith("/new");
  const alert = jobAlerts.find((item) => item.id === alertId);
  const [saved, setSaved] = useState(false);
  const [paused, setPaused] = useState(alert?.cadence === "Paused");
  if (!creating && !alert) return <CandidateShell><section className="candidate-page empty-state"><Bell size={28} /><h1>Job alert unavailable</h1><p>The alert may have been removed or is outside this candidate account.</p><NavLink className="primary-button" to="/job-alerts">Return to alerts</NavLink></section></CandidateShell>;
  if (creating || editing) {
    const submit = (event: FormEvent) => { event.preventDefault(); setSaved(true); announce(`${creating ? "New alert" : alert?.id} saved in browser memory with consent and locale.`); };
    return <CandidateShell><div className="candidate-page narrow-page"><NavLink className="back-link" to={alert ? `/job-alerts/${alert.id}` : "/job-alerts"}><ArrowLeft size={15} /> Job alerts</NavLink><section className="panel candidate-builder"><ScreenId>UI-CAN-008</ScreenId><span className="eyebrow">{creating ? "Create" : "Edit"} job alert</span><h1>{creating ? "Tell us what to watch for." : alert?.name}</h1>{saved ? <div className="completion-receipt"><CheckCircle2 size={23} /><div><strong>{creating ? "Alert JAL-MEM-001 created" : `${alert?.id} updated`}</strong><span>Memory-only receipt · candidate controlled</span></div><NavLink className="primary-button" to="/job-alerts">Return to alerts</NavLink></div> : <form className="portal-form" onSubmit={submit}><div className="form-grid"><label>Alert name<input defaultValue={alert?.name ?? "Design leadership · remote"} required /></label><label>Function<select defaultValue="Design"><option>Design</option><option>Engineering</option><option>Operations</option><option>All functions</option></select></label><label>Location<select defaultValue="US remote"><option>US remote</option><option>San Francisco hybrid</option><option>London hybrid</option><option>India</option></select></label><label>Level<select defaultValue="Senior and Staff"><option>All levels</option><option>Senior and Staff</option><option>Leadership</option><option>Early career</option></select></label><label>Cadence<select defaultValue={alert?.cadence === "Daily" ? "Daily" : "Weekly"}><option>Daily</option><option>Weekly</option></select></label><label>Channel<select defaultValue={alert?.channel ?? "Email"}><option>Email</option><option>Email + SMS</option></select></label><label>Language<select defaultValue={alert?.locale ?? "en-US"}><option>en-US</option><option>es-US</option><option>en-GB</option></select></label><label className="full checkbox-row"><input type="checkbox" defaultChecked />Send only matching-role alerts using this candidate-controlled permission.</label></div><button className="primary-button" type="submit">{creating ? "Create alert" : "Save alert changes"}</button></form>}</section></div></CandidateShell>;
  }
  if (!alert) return null;
  return <CandidateShell><div className="candidate-page narrow-page"><NavLink className="back-link" to="/job-alerts"><ArrowLeft size={15} /> All alerts</NavLink><section className="panel record-detail-page"><div className="panel-heading"><div><ScreenId>UI-CAN-008</ScreenId><span className="eyebrow">{alert.id} · {alert.locale}</span><h1>{alert.name}</h1><p>{alert.criteria}</p></div><Pill tone={paused ? "warning" : "success"}>{paused ? "Paused" : alert.cadence}</Pill></div><dl className="case-fact-grid"><div><dt>Criteria</dt><dd>{alert.criteria}</dd></div><div><dt>Cadence</dt><dd>{paused ? "Paused" : alert.cadence}</dd></div><div><dt>Channel</dt><dd>{alert.channel}</dd></div><div><dt>Last result</dt><dd>{alert.lastResult}</dd></div><div><dt>Authority</dt><dd>Candidate-controlled job-alert permission</dd></div><div><dt>Retention</dt><dd>Until paused, removed or relationship expiry</dd></div></dl><div className="detail-action-strip"><NavLink className="primary-button" to={`/job-alerts/${alert.id}/edit`}>Edit alert</NavLink><button className="secondary-button" onClick={() => setPaused((current) => !current)}>{paused ? "Resume alert" : "Pause alert"}</button><button className="danger-button" onClick={() => { announce(`${alert.id} removed in browser memory.`); navigate("/job-alerts"); }}>Remove alert</button></div></section></div></CandidateShell>;
}

function CandidateTaskWorkspace() {
  const { taskId } = useParams();
  const task = candidateTasks.find((item) => item.id === taskId);
  const detail = candidateTaskDetails.find((item) => item.id === taskId);
  const { announce } = usePrototype();
  const [noticeOpen, setNoticeOpen] = useState(false);
  const [confirmed, setConfirmed] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  if (!task || !detail) return <CandidateShell><section className="candidate-page empty-state"><FileCheck2 size={28} /><h1>Task unavailable</h1><p>The task may be complete, expired or outside this candidate relationship.</p><NavLink className="primary-button" to="/my-tasks">Return to tasks</NavLink></section></CandidateShell>;
  const submit = (event: FormEvent) => { event.preventDefault(); setSubmitted(true); announce(`${task.id} candidate action recorded in browser memory; internal review remains separate.`); };
  return <CandidateShell><div className="candidate-page narrow-page"><NavLink className="back-link" to="/my-tasks"><ArrowLeft size={15} /> Checks and tasks</NavLink><section className="candidate-task-workflow"><div className="panel"><div className="panel-heading"><div><ScreenId>UI-CAN-009</ScreenId><span className="eyebrow">{task.id} · {task.application}</span><h1>{task.title}</h1><p>{detail.purpose}</p></div><Pill tone={task.state === "Expired" || task.state === "Dispute open" ? "danger" : task.state === "Complete" ? "success" : "info"}>{submitted ? "Submitted" : task.state}</Pill></div><ol className="task-step-list">{detail.instructions.map((item, index) => <li key={item}><span>{index + 1}</span>{item}</li>)}</ol><button className="secondary-button" aria-expanded={noticeOpen} onClick={() => setNoticeOpen((open) => !open)}><ShieldCheck size={16} /> {noticeOpen ? "Hide notice" : "Review notice and rights"}</button>{noticeOpen && <div className="candidate-notice"><ShieldCheck size={20} /><div><h2>{task.noticeVersion}</h2><p>{detail.consent}</p><p>{detail.support}</p></div></div>}{submitted ? <div className="completion-receipt"><CheckCircle2 size={24} /><div><strong>{task.kind === "Adverse-action notice" ? "Correction response submitted" : task.state === "Expired" ? "Replacement requested" : "Candidate action saved"}</strong><span>Receipt TASK-MEM-{task.id} · decision automation prohibited</span></div></div> : <form className="portal-form" onSubmit={submit}>{detail.inputs.length > 0 && <div className="form-grid">{detail.inputs.map((input) => <label className={input.type === "textarea" ? "full" : ""} key={input.label}>{input.label}{input.type === "select" ? <select><option>Select…</option>{input.options?.map((option) => <option key={option}>{option}</option>)}</select> : input.type === "textarea" ? <textarea defaultValue="Synthetic correction detail for wireframe validation." /> : input.type === "checkbox" ? <input type="checkbox" /> : <input defaultValue="reference@example.test" />}</label>)}</div>}<label className="checkbox-row"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />I reviewed the current notice and understand this is a synthetic action.</label><button disabled={!confirmed} className="primary-button" type="submit">{task.kind === "Adverse-action notice" ? "Submit correction or dispute" : task.state === "Expired" ? "Request replacement" : "Submit candidate action"}</button></form>}</div><aside className="panel recovery-panel"><AlertTriangle size={23} /><h2>Failure and recovery</h2><dl><div><dt>Failure</dt><dd>{detail.failure}</dd></div><div><dt>Safe state</dt><dd>No candidate decision or duplicate provider effect</dd></div><div><dt>Recovery</dt><dd>{detail.recovery}</dd></div></dl><NavLink className="secondary-button" to={`/support/new?topic=${encodeURIComponent(task.kind)}`}>Get private support</NavLink></aside></section></div></CandidateShell>;
}

function EventContinuation() {
  const { eventId } = useParams();
  const location = useLocation();
  const { announce } = usePrototype();
  const event = careerEvents.find((item) => item.id === eventId);
  const [added, setAdded] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  if (!event) return <CandidateShell><section className="candidate-page empty-state"><CalendarDays size={28} /><h1>Event continuation unavailable</h1><NavLink className="primary-button" to="/events">Current events</NavLink></section></CandidateShell>;
  const feedback = location.pathname.endsWith("/feedback");
  if (feedback) return <CandidateShell><div className="candidate-page narrow-page"><NavLink className="back-link" to={`/events/${event.id}`}><ArrowLeft size={15} /> Event</NavLink><section className="panel candidate-builder"><ScreenId>UI-CAN-010</ScreenId><span className="eyebrow">Post-event experience · separated from hiring</span><h1>How was {event.name}?</h1>{submitted ? <div className="completion-receipt"><CheckCircle2 size={23} /><div><strong>Feedback saved</strong><span>Aggregated experience use only · no application created</span></div></div> : <form className="portal-form" onSubmit={(e) => { e.preventDefault(); setSubmitted(true); announce("Event feedback saved in browser memory."); }}><label>Experience rating<select><option>5 · Excellent</option><option>4 · Good</option><option>3 · Neutral</option><option>2 · Needs improvement</option><option>1 · Poor</option></select></label><label>What helped or could improve?<textarea defaultValue="The accessible agenda and clear event-only privacy notice were helpful." /></label><label className="checkbox-row"><input type="checkbox" />I want to hear about similar events. This does not authorize job marketing.</label><button className="primary-button" type="submit">Submit event feedback</button></form>}</section></div></CandidateShell>;
  return <CandidateShell><div className="candidate-page narrow-page"><NavLink className="back-link" to={`/events/${event.id}`}><ArrowLeft size={15} /> Event details</NavLink><section className="panel event-ticket"><div><TicketCheck size={38} /><ScreenId>UI-CAN-010</ScreenId><span className="eyebrow">Registration ERG-MEM-001</span><h1>{event.name}</h1><p>{event.date} · {event.format}</p><div className="ticket-code" aria-label="Synthetic event ticket code">HARBOR-EVT-{event.id.slice(-3)}</div></div><aside><Pill tone="success">Registered</Pill><dl><div><dt>Check-in</dt><dd>Opens 30 minutes before</dd></div><div><dt>Authority</dt><dd>Event-only updates</dd></div><div><dt>Accessibility</dt><dd>Private support retained</dd></div></dl><button className="primary-button" onClick={() => { setAdded(true); announce("Event calendar preview created with timezone and cancellation metadata."); }}>{added ? "Calendar preview ready" : "Add event to calendar"}</button><NavLink className="secondary-button" to={`/events/${event.id}/feedback`}>Preview post-event journey</NavLink></aside></section></div></CandidateShell>;
}

function SupportWorkspace() {
  const { caseId } = useParams();
  const location = useLocation();
  const { announce } = usePrototype();
  const [created, setCreated] = useState(false);
  const [reply, setReply] = useState(false);
  const item = supportCases.find((row) => row.id === caseId);
  if (location.pathname.endsWith("/new")) return <CandidateShell><div className="candidate-page narrow-page"><NavLink className="back-link" to="/support"><ArrowLeft size={15} /> Support cases</NavLink><section className="panel candidate-builder"><ScreenId>UI-CAN-011</ScreenId><h1>Start a private support request.</h1><p>Support details remain separated from interviewers and hiring evidence.</p>{created ? <div className="completion-receipt"><CheckCircle2 size={23} /><div><strong>Support case SUP-MEM-001 created</strong><span>Candidate-safe receipt · memory only</span></div><NavLink className="primary-button" to="/support">View support cases</NavLink></div> : <form className="portal-form" onSubmit={(e) => { e.preventDefault(); setCreated(true); announce("Private candidate support case created in memory."); }}><div className="form-grid"><label>Topic<select defaultValue={new URLSearchParams(location.search).get("topic") ?? "Application support"}><option>Application support</option><option>Assessment</option><option>Reference</option><option>Background check</option><option>Accessibility</option><option>Interview technology</option></select></label><label>Preferred contact<select><option>Secure portal</option><option>Email</option><option>Phone callback</option></select></label><label className="full">What do you need?<textarea defaultValue="Please use the prepared synthetic support scenario." /></label><label className="full checkbox-row"><input type="checkbox" defaultChecked />Keep these details out of interviewer and decision-maker views.</label></div><button className="primary-button" type="submit">Create private request</button></form>}</section></div></CandidateShell>;
  if (caseId && !item) return <CandidateShell><section className="candidate-page empty-state"><CircleHelp size={28} /><h1>Support case unavailable</h1><NavLink className="primary-button" to="/support">Return to support</NavLink></section></CandidateShell>;
  if (item) return <CandidateShell><div className="candidate-page narrow-page"><NavLink className="back-link" to="/support"><ArrowLeft size={15} /> Support</NavLink><section className="panel record-detail-page"><div className="panel-heading"><div><ScreenId>UI-CAN-011</ScreenId><span className="eyebrow">{item.id}</span><h1>{item.topic}</h1><p>{item.updated}</p></div><Pill tone={item.status === "Resolved" ? "success" : item.status === "Waiting for you" ? "warning" : "info"}>{item.status}</Pill></div><dl className="case-fact-grid"><div><dt>Owner</dt><dd>{item.owner}</dd></div><div><dt>Next action</dt><dd>{reply ? "Candidate reply received" : item.next}</dd></div><div><dt>Visibility</dt><dd>Candidate Support and purpose-bound specialist</dd></div><div><dt>Hiring evidence</dt><dd>Excluded</dd></div></dl><div className="candidate-message-center"><section><article className="candidate-thread-item inbound"><h3>We received your request</h3><p>We can help without sharing private details with interviewers.</p><small>Today · candidate-safe support thread</small></article>{reply && <article className="candidate-thread-item outbound"><h3>Your reply</h3><p>Please continue with the prepared synthetic resolution.</p><small>Just now · memory only</small></article>}</section></div><button className="primary-button" onClick={() => { setReply(true); announce(`${item.id} reply saved in browser memory.`); }}>Reply securely</button></section></div></CandidateShell>;
  return <CandidateShell><div className="candidate-page relationship-page"><div className="hub-welcome"><div><ScreenId>UI-CAN-011</ScreenId><span className="eyebrow">Candidate support</span><h1>Help without hiring consequences.</h1><p>Private support, accommodations, corrections and technical requests remain separated from evaluation.</p></div><NavLink className="primary-button" to="/support/new">New support request</NavLink></div><section className="panel role-record-list">{supportCases.map((row) => <NavLink to={`/support/${row.id}`} key={row.id}><span><MessageCircleQuestion size={20} /></span><span><strong>{row.topic}</strong><small>{row.id} · {row.updated}</small></span><span><strong>{row.owner}</strong><small>{row.next}</small></span><Pill tone={row.status === "Resolved" ? "success" : row.status === "Waiting for you" ? "warning" : "info"}>{row.status}</Pill></NavLink>)}</section></div></CandidateShell>;
}

function PrivacyWorkspace() {
  const { requestId } = useParams();
  const location = useLocation();
  const { announce } = usePrototype();
  const [created, setCreated] = useState(false);
  const item = privacyCases.find((row) => row.id === requestId);
  if (location.pathname.endsWith("/new")) return <CandidateShell><div className="candidate-page narrow-page"><NavLink className="back-link" to="/privacy-requests"><ArrowLeft size={15} /> Privacy requests</NavLink><section className="panel candidate-builder"><ScreenId>UI-CAN-012</ScreenId><ShieldCheck size={28} /><h1>Exercise a privacy right safely.</h1>{created ? <div className="completion-receipt"><CheckCircle2 size={23} /><div><strong>Privacy request PRI-MEM-001 created</strong><span>Identity verification is required before execution.</span></div></div> : <form className="portal-form" onSubmit={(e) => { e.preventDefault(); setCreated(true); announce("Privacy request created in browser memory."); }}><label>Request type<select><option>Access copy</option><option>Correction</option><option>Deletion</option><option>Restriction or objection</option><option>Consent withdrawal</option></select></label><label>Scope<select><option>Candidate profile and applications</option><option>Talent community relationship</option><option>Event registrations</option><option>Support cases</option></select></label><label>Details<textarea defaultValue="Use the prepared synthetic privacy-request scenario." /></label><label className="checkbox-row"><input type="checkbox" required />I understand identity and retention checks occur before execution.</label><button className="primary-button" type="submit">Submit privacy request</button></form>}</section></div></CandidateShell>;
  if (requestId && !item) return <CandidateShell><section className="candidate-page empty-state"><ShieldCheck size={28} /><h1>Privacy request unavailable</h1><NavLink className="primary-button" to="/privacy-requests">Return to requests</NavLink></section></CandidateShell>;
  if (item) return <CandidateShell><div className="candidate-page narrow-page"><NavLink className="back-link" to="/privacy-requests"><ArrowLeft size={15} /> Privacy requests</NavLink><section className="panel record-detail-page"><div className="panel-heading"><div><ScreenId>UI-CAN-012</ScreenId><span className="eyebrow">{item.id} · {item.type}</span><h1>{item.scope}</h1><p>Due {item.due}</p></div><Pill tone="info">{item.status}</Pill></div><ol className="task-step-list"><li><span>1</span>Request received</li><li><span>2</span>Identity verification</li><li><span>3</span>Retention, legal-hold and scope review</li><li><span>4</span>Execution and external reconciliation</li><li><span>5</span>Candidate-safe response package</li></ol><div className="candidate-notice"><LockKeyhole size={20} /><div><h2>Current next action</h2><p>{item.next}. No data is exported or deleted in this public wireframe.</p></div></div></section></div></CandidateShell>;
  return <CandidateShell><div className="candidate-page relationship-page"><div className="hub-welcome"><div><ScreenId>UI-CAN-012</ScreenId><span className="eyebrow">Privacy and data rights</span><h1>Understand and control your information.</h1><p>Every request has identity, scope, retention, external-system and completion evidence.</p></div><NavLink className="primary-button" to="/privacy-requests/new">New privacy request</NavLink></div><section className="panel role-record-list">{privacyCases.map((row) => <NavLink to={`/privacy-requests/${row.id}`} key={row.id}><span><ShieldCheck size={20} /></span><span><strong>{row.type}</strong><small>{row.id} · {row.scope}</small></span><span><strong>{row.next}</strong><small>Due {row.due}</small></span><Pill tone="info">{row.status}</Pill></NavLink>)}</section></div></CandidateShell>;
}

export function CandidateSystemWorkspace() {
  const location = useLocation();
  if (location.pathname.startsWith("/sign-in") || location.pathname === "/account-recovery") return <CandidateAccess />;
  if (location.pathname.startsWith("/job-alerts/")) return <AlertWorkspace />;
  if (location.pathname.startsWith("/my-tasks/")) return <CandidateTaskWorkspace />;
  if (location.pathname.includes("/ticket") || location.pathname.includes("/feedback")) return <EventContinuation />;
  if (location.pathname.startsWith("/privacy-requests")) return <PrivacyWorkspace />;
  return <SupportWorkspace />;
}
