import { useState } from "react";
import { NavLink, useLocation, useParams } from "react-router-dom";
import { AlertTriangle, ArrowLeft, BookOpenCheck, BriefcaseBusiness, Building2, CheckCircle2, FileCheck2, Globe2, GraduationCap, Laptop, LockKeyhole, Plus, RefreshCcw, ShieldCheck, UserRoundCheck } from "lucide-react";
import { benefitElections, learningEnrollments, transitionCases, type JourneyStatus } from "../data/fullSystem";
import { localeVariants } from "../data/lifecycleDepth";
import { usePrototype } from "../prototype/PrototypeContext";
import { Pill, ScreenId } from "./Common";
import { HrShell } from "./HrWorkspace";
import { PortalFrame } from "./NewHirePortal";

function tone(state: JourneyStatus | string) {
  if (["Complete", "Active", "Approved demo"].includes(state)) return "success" as const;
  if (["Blocked", "Cancelled", "Incomplete"].includes(state)) return "danger" as const;
  if (state === "Draft") return "neutral" as const;
  return "warning" as const;
}

function BenefitsPortal() {
  const { benefitId } = useParams();
  const { announce } = usePrototype();
  const item = benefitElections.find((row) => row.id === benefitId);
  const [submitted, setSubmitted] = useState(false);
  const [waived, setWaived] = useState(false);
  if (benefitId && !item) return <PortalFrame><section className="portal-page empty-state"><FileCheck2 size={28} /><h1>Benefit election unavailable</h1><NavLink className="primary-button" to="/preboarding/benefits">Return to benefits</NavLink></section></PortalFrame>;
  if (item) return <PortalFrame><section className="portal-page"><NavLink className="back-link" to="/preboarding/benefits"><ArrowLeft size={15} /> Benefits</NavLink><div className="portal-page-heading simple"><div><ScreenId>UI-NHR-009</ScreenId><span className="eyebrow">{item.id} · {item.country}</span><h1>{item.plan}</h1><p>Effective {item.effective} · choose by {item.deadline}</p></div><Pill tone={tone(submitted ? "Complete" : item.status)}>{submitted ? "Election submitted" : item.status}</Pill></div>{submitted ? <div className="completion-receipt"><CheckCircle2 size={24} /><div><strong>{waived ? "Coverage waived" : "Election saved"}</strong><span>BEN-REC-MEM-001 · plan version {item.evidence} · memory only</span></div></div> : <div className="profile-layout"><form className="panel portal-form" onSubmit={(e) => { e.preventDefault(); setSubmitted(true); announce(`${item.id} benefit election saved in browser memory.`); }}><fieldset><legend>Coverage election</legend><label>Coverage<select defaultValue={item.coverage} onChange={(e) => setWaived(e.target.value.startsWith("Waive"))}><option>Employee</option><option>Employee + partner</option><option>Family</option><option>Waive with reason</option></select></label><label>Plan option<select><option>Standard synthetic plan</option><option>Enhanced synthetic plan</option><option>High-deductible synthetic plan</option></select></label>{waived && <label>Waiver reason<select><option>Covered by another plan</option><option>Decline coverage</option><option>Other prepared reason</option></select></label>}<label>Dependent fixture<select><option>No dependents</option><option>Prepared spouse fixture</option><option>Prepared family fixture</option></select></label><label className="checkbox-row"><input type="checkbox" required />I reviewed the country plan, cost and effective-date preview.</label></fieldset><button className="primary-button" type="submit">Submit synthetic election</button></form><aside className="panel privacy-explainer"><LockKeyhole size={23} /><h2>Restricted data boundary</h2><p>Real dependent, health, bank or tax data is not collected here. HR operations receives only completion and reconciliation status.</p></aside></div>}</section></PortalFrame>;
  return <PortalFrame><section className="portal-page"><div className="portal-page-heading simple"><div><ScreenId>UI-NHR-009</ScreenId><span className="eyebrow">Benefits and payroll readiness</span><h1>Choose with clear dates and country context.</h1><p>Each election binds plan, country, effective date, coverage and completion evidence.</p></div><Pill tone="warning">{benefitElections.filter((row) => row.status !== "Complete").length} actions</Pill></div><div className="document-center-grid">{benefitElections.map((row) => <article key={row.id}><span className="document-type-icon"><FileCheck2 size={22} /></span><div><small>{row.id} · {row.country}</small><h2>{row.plan}</h2><p>{row.coverage} · deadline {row.deadline}</p><dl><div><dt>Effective</dt><dd>{row.effective}</dd></div><div><dt>Pack</dt><dd>{row.evidence}</dd></div></dl></div><Pill tone={tone(row.status)}>{row.status}</Pill><NavLink className="primary-button" to={`/preboarding/benefits/${row.id}`}>Review election</NavLink></article>)}</div></section></PortalFrame>;
}

function LearningPortal() {
  const { learningId } = useParams();
  const { announce } = usePrototype();
  const item = learningEnrollments.find((row) => row.id === learningId);
  const [progress, setProgress] = useState(0);
  if (learningId && !item) return <PortalFrame><section className="portal-page empty-state"><GraduationCap size={28} /><h1>Learning item unavailable</h1><NavLink className="primary-button" to="/preboarding/learning">Return to learning</NavLink></section></PortalFrame>;
  if (item) return <PortalFrame><section className="portal-page"><NavLink className="back-link" to="/preboarding/learning"><ArrowLeft size={15} /> Learning</NavLink><div className="portal-page-heading simple"><div><ScreenId>UI-NHR-010</ScreenId><span className="eyebrow">{item.id} · {item.type}</span><h1>{item.title}</h1><p>{item.duration} · due {item.due}</p></div><Pill tone={tone(progress === 100 ? "Complete" : item.status)}>{progress === 100 ? "Complete" : `${progress}%`}</Pill></div><div className="learning-detail-grid"><section className="panel"><h2>Accessible learning session</h2><p>{item.accessibility}</p><div className="progress-track"><i style={{ width: `${progress}%` }} /></div><ol className="task-step-list"><li><span>1</span>Context and learning objectives</li><li><span>2</span>Accessible content and transcript</li><li><span>3</span>Prepared knowledge check</li><li><span>4</span>Completion receipt and optional feedback</li></ol><div className="detail-action-strip"><button disabled={progress >= 25} className="secondary-button" onClick={() => setProgress(25)}>Start module</button><button disabled={progress < 25 || progress >= 75} className="secondary-button" onClick={() => setProgress(75)}>Complete content</button><button disabled={progress < 75 || progress === 100} className="primary-button" onClick={() => { setProgress(100); announce(`${item.id} learning completion saved in memory.`); }}>Submit knowledge check</button></div></section><aside className="panel"><BookOpenCheck size={24} /><h2>Prerequisite and alternatives</h2><dl><div><dt>Prerequisite</dt><dd>{item.prerequisite}</dd></div><div><dt>Alternative</dt><dd>Transcript and facilitated accessible session</dd></div><div><dt>Manager view</dt><dd>Completion only</dd></div></dl></aside></div></section></PortalFrame>;
  return <PortalFrame><section className="portal-page"><div className="portal-page-heading simple"><div><ScreenId>UI-NHR-010</ScreenId><span className="eyebrow">Learning curriculum</span><h1>Know what to learn and why.</h1><p>Sessions, prerequisites, accessibility alternatives, progress and completion evidence stay together.</p></div><Pill tone="info">{learningEnrollments.length} enrollments</Pill></div><div className="learning-catalog-grid">{learningEnrollments.map((row) => <NavLink to={`/preboarding/learning/${row.id}`} key={row.id}><GraduationCap size={22} /><span><small>{row.id} · {row.type}</small><strong>{row.title}</strong><em>{row.duration} · {row.due}</em></span><Pill tone={tone(row.status)}>{row.status}</Pill></NavLink>)}</div></section></PortalFrame>;
}

function CountryOnboarding() {
  const { localeId } = useParams();
  const item = localeVariants.find((row) => row.id === localeId);
  const { announce } = usePrototype();
  const [step, setStep] = useState(0);
  if (!item) return <PortalFrame><section className="portal-page empty-state"><Globe2 size={28} /><h1>Country onboarding pack unavailable</h1><NavLink className="primary-button" to="/preboarding">Return home</NavLink></section></PortalFrame>;
  const blocked = item.reviewState === "Incomplete";
  const steps = ["Welcome", "Forms", "Pay and benefits", "Signature", "Support"];
  return <PortalFrame><section className="portal-page"><div className="portal-page-heading simple"><div><ScreenId>UI-NHR-011</ScreenId><span className="eyebrow">{item.id} · {item.locale} · {item.workerType}</span><h1>{item.country} onboarding experience</h1><p>{item.language} · approved content and forms are version-bound.</p></div><Pill tone={tone(item.reviewState)}>{item.reviewState}</Pill></div>{blocked ? <section className="panel access-denied"><AlertTriangle size={28} /><div><h2>Localized onboarding is blocked</h2><p>Required content, forms or support coverage is incomplete. No silent fallback is used.</p></div></section> : <><div className="candidate-hub-tabs" role="tablist" aria-label="Country onboarding steps">{steps.map((name, index) => <button role="tab" aria-selected={step === index} onClick={() => setStep(index)} key={name}>{name}</button>)}</div><section className="panel country-onboarding-preview"><h2>{steps[step]}</h2>{step === 0 && <dl className="case-fact-grid"><div><dt>Notice pack</dt><dd>{item.noticePack}</dd></div><div><dt>Language</dt><dd>{item.language}</dd></div><div><dt>Worker type</dt><dd>{item.workerType}</dd></div><div><dt>Start model</dt><dd>Country-aware effective date</dd></div></dl>}{step === 1 && <div className="document-center-grid"><article><FileCheck2 size={22} /><h3>{item.formPack}</h3><p>Country employment and payroll forms with restricted storage.</p><button className="secondary-button" onClick={() => announce(`${item.formPack} accessible form preview opened.`)}>Open forms preview</button></article></div>}{step === 2 && <dl className="case-fact-grid"><div><dt>Pay display</dt><dd>{item.payDisplay}</dd></div><div><dt>Benefits</dt><dd>Country-qualified plan catalogue</dd></div><div><dt>Payroll</dt><dd>Restricted provider-safe completion</dd></div><div><dt>Tax</dt><dd>Secure country form route</dd></div></dl>}{step === 3 && <div className="candidate-notice"><ShieldCheck size={21} /><div><h3>{item.signature}</h3><p>The exact current document, signature method, signer identity and receipt remain bound.</p></div></div>}{step === 4 && <div className="help-card-grid"><article><Globe2 size={23} /><h3>Local People Operations</h3><p>{item.language} support route and escalation hours.</p></article><article><LockKeyhole size={23} /><h3>Private support</h3><p>Tax, eligibility, accessibility and correction stay purpose-limited.</p></article></div>}</section></>}</section></PortalFrame>;
}

function TransitionOperations() {
  const { transitionId } = useParams();
  const location = useLocation();
  const { announce } = usePrototype();
  const item = transitionCases.find((row) => row.id === transitionId);
  const creating = location.pathname.endsWith("/new");
  const editing = location.pathname.endsWith("/edit");
  const impact = location.pathname.endsWith("/impact");
  const [saved, setSaved] = useState(false);
  const [checks, setChecks] = useState<string[]>([]);
  const [state, setState] = useState<JourneyStatus>(item?.status ?? "Draft");
  const [filter, setFilter] = useState("All");
  if (creating || editing) return <HrShell title={creating ? "Create worker transition" : `Edit ${item?.id ?? "transition"}`} eyebrow="Effective-dated lifecycle change" screenId="UI-HR-021" screen="onboarding"><section className="panel admin-form-page"><NavLink className="back-link" to={item ? `/hr/transitions/${item.id}` : "/hr/transitions"}><ArrowLeft size={15} /> Transitions</NavLink>{saved ? <div className="completion-receipt"><CheckCircle2 size={23} /><div><strong>{creating ? "Transition TRN-MEM-001 created" : "Transition version saved"}</strong><span>Impact preview and approval remain required before release.</span></div></div> : <form className="portal-form" onSubmit={(e) => { e.preventDefault(); setSaved(true); announce("Worker transition draft saved in browser memory."); }}><div className="form-grid"><label>Person fixture<select><option>Maya Chen</option><option>Noah Williams</option><option>Sofia Rodriguez</option></select></label><label>Transition type<select defaultValue={item?.type ?? "Crossboarding"}><option>Rehire</option><option>Crossboarding</option><option>Relocation</option><option>Contingent</option><option>Offboarding</option><option>Rescission</option><option>Delayed start</option><option>No show</option></select></label><label>Effective date<input type="date" defaultValue={item?.effective ?? "2026-09-15"} /></label><label>Owner<select><option>People Operations</option><option>HRIS Operations</option><option>Recruiter</option><option>Manager</option></select></label><label className="full">Reason and safe context<textarea defaultValue="Prepared synthetic lifecycle-transition reason." /></label><label className="full checkbox-row"><input type="checkbox" defaultChecked />Generate impact preview across identity, tasks, documents, payroll, benefits, access and facilities.</label></div><button className="primary-button" type="submit">Save transition draft</button></form>}</section></HrShell>;
  if (transitionId && !item) return <HrShell title="Transition unavailable" eyebrow={transitionId} screenId="UI-HR-021" screen="onboarding"><section className="panel empty-state"><RefreshCcw size={28} /><h2>Worker transition not found</h2><NavLink className="primary-button" to="/hr/transitions">Return to transitions</NavLink></section></HrShell>;
  if (item && impact) return <HrShell title={`${item.type} impact preview`} eyebrow={`${item.id} · effective ${item.effective}`} screenId="UI-HR-021" screen="onboarding"><div className="system-detail-grid"><section className="panel"><h2>Affected journeys and compensating work</h2><div className="impact-grid">{item.affected.map((area) => { const done = checks.includes(area); return <article key={area}><span>{area === "Access" ? <Laptop size={21} /> : area === "Facilities" ? <Building2 size={21} /> : <ClipboardIcon />}</span><div><strong>{area}</strong><small>{item.type === "Offboarding" || item.type === "Rescission" ? "Cancel/revoke and reconcile" : "Re-evaluate effective state"}</small></div><label><input type="checkbox" checked={done} onChange={() => setChecks((current) => done ? current.filter((x) => x !== area) : [...current, area])} /> Reviewed</label></article>; })}</div><button disabled={checks.length !== item.affected.length} className="primary-button" onClick={() => { setState("Ready"); announce(`${item.id} impact preview approved in memory.`); }}>Approve complete impact preview</button></section><aside className="panel recovery-panel"><AlertTriangle size={23} /><h2>Failure contract</h2><p>{item.failure}. Release is blocked until affected destinations and owners are known.</p></aside></div></HrShell>;
  if (item) return <HrShell title={`${item.type} · ${item.person}`} eyebrow={`${item.id} · effective ${item.effective}`} screenId="UI-HR-021" screen="onboarding" actions={<NavLink className="secondary-button" to={`/hr/transitions/${item.id}/edit`}>Edit draft</NavLink>}><div className="system-detail-grid"><section className="panel record-detail-page"><div className="panel-heading"><div><span className="eyebrow">Owner {item.owner}</span><h2>{item.nextAction}</h2></div><Pill tone={tone(state)}>{state}</Pill></div><dl className="case-fact-grid"><div><dt>Type</dt><dd>{item.type}</dd></div><div><dt>Effective date</dt><dd>{item.effective}</dd></div><div><dt>Affected</dt><dd>{item.affected.join(" · ")}</dd></div><div><dt>Failure</dt><dd>{item.failure}</dd></div></dl><div className="detail-action-strip"><NavLink className="primary-button" to={`/hr/transitions/${item.id}/impact`}>Run impact preview</NavLink><button className="secondary-button" onClick={() => { setState("Active"); announce(`${item.id} released in browser memory after preview.`); }}>Release transition</button><button className="danger-button" onClick={() => { setState("Cancelled"); announce(`${item.id} cancelled with downstream compensation preview.`); }}>Cancel transition</button></div></section><aside className="panel"><ShieldCheck size={23} /><h2>Invariant</h2><p>Effective-dated transitions update or revoke the right tasks and access without overwriting historical worker or candidate identity.</p></aside></div></HrShell>;
  const rows = transitionCases.filter((row) => filter === "All" || row.type === filter);
  return <HrShell title="Worker transition operations" eyebrow="Rehire, crossboard, relocate, contingent and exit" screenId="UI-HR-021" screen="onboarding" actions={<NavLink className="primary-button" to="/hr/transitions/new"><Plus size={15} /> New transition</NavLink>}><section className="onboarding-metrics"><article><UserRoundCheck size={19} /><span><strong>{transitionCases.length}</strong>Transitions</span></article><article><BriefcaseBusiness size={19} /><span><strong>{transitionCases.filter((r) => r.type === "Crossboarding").length}</strong>Crossboarding</span></article><article><Laptop size={19} /><span><strong>{transitionCases.filter((r) => ["Offboarding", "Rescission", "No show"].includes(r.type)).length}</strong>Revocation journeys</span></article><article><AlertTriangle size={19} /><span><strong>{transitionCases.filter((r) => r.status === "Blocked").length}</strong>Blocked</span></article></section><section className="panel lifecycle-table-panel"><div className="table-toolbar"><label>Type<select value={filter} onChange={(e) => setFilter(e.target.value)}><option>All</option>{[...new Set(transitionCases.map((r) => r.type))].map((type) => <option key={type}>{type}</option>)}</select></label><Pill tone="info">{rows.length} transitions</Pill></div><div className="operations-record-grid">{rows.map((row) => <NavLink to={`/hr/transitions/${row.id}`} key={row.id}><RefreshCcw size={20} /><span><small>{row.id} · {row.type}</small><strong>{row.person}</strong><em>{row.effective} · {row.owner}</em></span><span><strong>{row.nextAction}</strong><small>{row.affected.join(" · ")}</small></span><Pill tone={tone(row.status)}>{row.status}</Pill></NavLink>)}</div></section></HrShell>;
}

function ClipboardIcon() { return <ClipboardCheckIcon />; }
function ClipboardCheckIcon() { return <span aria-hidden="true">✓</span>; }

export function LifecycleV3() {
  const path = useLocation().pathname;
  if (path.startsWith("/preboarding/benefits")) return <BenefitsPortal />;
  if (path.startsWith("/preboarding/learning")) return <LearningPortal />;
  if (path.startsWith("/preboarding/country")) return <CountryOnboarding />;
  return <TransitionOperations />;
}
