import { useState, type FormEvent } from "react";
import { NavLink, useLocation, useParams } from "react-router-dom";
import { AlertTriangle, ArrowLeft, Building2, CalendarCheck2, CheckCircle2, ClipboardCheck, Globe2, Handshake, Plus, RefreshCcw, Search, ShieldCheck, UserCheck, UsersRound } from "lucide-react";
import { agencyAssignments, highVolumeCohorts, recruitingEventAdmin } from "../data/fullSystem";
import { highVolumeCampaigns, localeVariants, recoveryScenarios } from "../data/lifecycleDepth";
import { usePrototype } from "../prototype/PrototypeContext";
import { Pill, ScreenId } from "./Common";
import { HrShell } from "./HrWorkspace";

function tone(state: string) {
  if (["Complete", "Resolved", "Approved demo", "Active"].includes(state)) return "success" as const;
  if (["Blocked", "Incomplete", "Cancelled"].includes(state)) return "danger" as const;
  if (["Draft", "Planning"].includes(state)) return "neutral" as const;
  return "warning" as const;
}

function OperationsNav() {
  return <nav className="workspace-subnav" aria-label="Recruiting operations"><NavLink to="/hr/high-volume">Campaigns</NavLink><NavLink to="/hr/high-volume/HVC-001/planning">Capacity plan</NavLink><NavLink to="/hr/high-volume/HVC-001/analytics">Cohort analytics</NavLink><NavLink to="/hr/events">Events</NavLink><NavLink to="/hr/locales">Locale packs</NavLink><NavLink to="/hr/recovery">Recovery</NavLink><NavLink to="/hr/agency-assignments">Agency assignments</NavLink></nav>;
}

function HighVolumePlanning() {
  const { campaignId } = useParams();
  const location = useLocation();
  const { announce } = usePrototype();
  const campaign = highVolumeCampaigns.find((row) => row.id === campaignId);
  const cohorts = highVolumeCohorts.filter((row) => row.campaignId === campaignId);
  const analytics = location.pathname.endsWith("/analytics");
  const [reviewers, setReviewers] = useState(12);
  const [weeklyCapacity, setWeeklyCapacity] = useState(280);
  const [saved, setSaved] = useState(false);
  const [shared, setShared] = useState(false);
  if (!campaign) return <HrShell title="Campaign planning unavailable" eyebrow={campaignId ?? "Unknown"} screenId="UI-HR-017" screen="high-volume"><OperationsNav /><section className="panel empty-state"><UsersRound size={28} /><h2>Campaign not found</h2><NavLink className="primary-button" to="/hr/high-volume">Return to campaigns</NavLink></section></HrShell>;
  if (analytics) {
    const total = cohorts.reduce((sum, row) => sum + row.applications, 0) || campaign.applicants;
    return <HrShell title={`${campaign.name} cohort analytics`} eyebrow={`${campaign.id} · cohort conversion and capacity`} screenId="UI-HR-017" screen="high-volume"><OperationsNav /><section className="onboarding-metrics"><article><UsersRound size={19} /><span><strong>{total.toLocaleString()}</strong>Applications</span></article><article><UserCheck size={19} /><span><strong>{cohorts.reduce((sum, row) => sum + row.ready, 0)}</strong>Ready after deterministic checks</span></article><article><Building2 size={19} /><span><strong>{cohorts.reduce((sum, row) => sum + row.capacity, 0)}</strong>Human capacity</span></article><article><AlertTriangle size={19} /><span><strong>{cohorts.reduce((sum, row) => sum + row.exceptions, 0)}</strong>Exceptions</span></article></section><section className="panel cohort-analytics"><div className="panel-heading"><div><h2>Conversion by cohort</h2><span>Descriptive operations only; never a candidate ranking signal.</span></div><Pill tone="info">Source cohort snapshot v3</Pill></div>{cohorts.map((row) => { const rate = row.applications ? Math.round((row.ready / row.applications) * 100) : null; return <article key={row.id}><div><strong>{row.name}</strong><small>{row.id} · {row.state}</small></div><div className="progress-track"><i style={{ width: `${rate ?? 0}%` }} /></div><span>{rate === null ? "N/A" : `${rate}%`} ready</span><NavLink to={`/hr/high-volume/${campaign.id}/cohorts/${row.id}`}>Drill through</NavLink></article>; })}</section></HrShell>;
  }
  const weeks = Math.max(1, Math.ceil(campaign.applicants / weeklyCapacity));
  const reviewerLoad = Math.ceil(weeklyCapacity / reviewers);
  return <HrShell title={`${campaign.name} capacity plan`} eyebrow={`${campaign.id} · reviewers, throughput and saved views`} screenId="UI-HR-017" screen="high-volume"><OperationsNav /><div className="system-detail-grid"><section className="panel portal-form-page"><div className="panel-heading"><div><h2>Human-capacity scenario</h2><span>No candidate decision is automated.</span></div><Pill tone={reviewerLoad > 30 ? "warning" : "success"}>{reviewerLoad} reviews/person/week</Pill></div><div className="form-grid"><label>Reviewers<input type="number" min="1" value={reviewers} onChange={(event) => setReviewers(Math.max(1, Number(event.target.value)))} /></label><label>Weekly human-review capacity<input type="number" min="1" value={weeklyCapacity} onChange={(event) => setWeeklyCapacity(Math.max(1, Number(event.target.value)))} /></label><label>Hours per review<input type="number" defaultValue="0.75" step="0.25" /></label><label>Buffer<select><option>20% protected exception buffer</option><option>30% launch buffer</option><option>10% steady-state buffer</option></select></label></div><section className="onboarding-metrics"><article><UsersRound size={19} /><span><strong>{weeks}</strong>Weeks to clear current volume</span></article><article><ClipboardCheck size={19} /><span><strong>{reviewerLoad}</strong>Weekly load per reviewer</span></article><article><AlertTriangle size={19} /><span><strong>{cohorts.reduce((sum, row) => sum + row.exceptions, 0)}</strong>Exception demand</span></article><article><Building2 size={19} /><span><strong>{reviewers}</strong>Human reviewers</span></article></section><div className="detail-action-strip"><button className="secondary-button" onClick={() => { setSaved(true); announce(`${campaign.id} capacity scenario saved in browser memory.`); }}>{saved ? "Saved view: Launch capacity" : "Save capacity view"}</button><button className="primary-button" onClick={() => { setShared(true); announce(`${campaign.id} saved-view share preview created with recipient scope and expiry.`); }}>{shared ? "Share preview ready" : "Share saved view"}</button></div>{shared && <div className="inline-confirm"><strong>Scoped share preview</strong><span>Recipients: campaign owner + assigned review leads · expires Sep 30 · aggregate data only.</span></div>}</section><aside className="panel recovery-panel"><AlertTriangle size={23} /><h2>Capacity guardrails</h2><ul><li>Stop invitations before human capacity is exceeded</li><li>Reserve explicit exception capacity</li><li>Do not infer candidate quality from throughput</li><li>Restate views when cohort membership changes</li></ul></aside></div></HrShell>;
}

function EventOperations() {
  const { eventId } = useParams();
  const location = useLocation();
  const { announce } = usePrototype();
  const event = recruitingEventAdmin.find((item) => item.id === eventId);
  const creating = location.pathname.endsWith("/new");
  const editing = location.pathname.endsWith("/edit");
  const checkIn = location.pathname.endsWith("/check-in");
  const [saved, setSaved] = useState(false);
  const [checkedIn, setCheckedIn] = useState<string[]>([]);
  const [query, setQuery] = useState("");
  const attendees = Array.from({ length: 18 }, (_, index) => ({ id: `ERG-${eventId}-${index + 1}`, name: ["Maya Chen", "Noah Williams", "Sofia Rodriguez", "Liam Patel", "Ava Thompson", "Ethan Kim"][index % 6], ticket: `TKT-${String(8100 + index)}`, state: index % 5 === 0 ? "Waitlisted" : index % 4 === 0 ? "Cancelled" : "Registered", accessibility: index % 7 === 0 ? "Private route" : "None" }));
  if (creating || editing) {
    const submit = (e: FormEvent) => { e.preventDefault(); setSaved(true); announce(`${creating ? "Event REV-MEM-001 created" : `${event?.id} updated`} in browser memory.`); };
    return <HrShell title={creating ? "Create recruiting event" : `Edit ${event?.name ?? "event"}`} eyebrow="Versioned event configuration" screenId="UI-HR-016" screen="high-volume"><OperationsNav /><section className="panel admin-form-page"><NavLink className="back-link" to={event ? `/hr/events/${event.id}` : "/hr/events"}><ArrowLeft size={15} /> Events</NavLink>{saved ? <div className="completion-receipt"><CheckCircle2 size={23} /><div><strong>{creating ? "Event REV-MEM-001 created in Draft" : "Event version saved"}</strong><span>Publishing remains a separate governed action.</span></div></div> : <form className="portal-form" onSubmit={submit}><div className="form-grid"><label>Name<input defaultValue={event?.name ?? "Product and design open house"} required /></label><label>Type<select defaultValue={event?.type ?? "Open house"}><option>Open house</option><option>Campus</option><option>Hiring event</option><option>Community</option></select></label><label>Date and time<input defaultValue="2026-09-18T16:00" type="datetime-local" /></label><label>Timezone<select><option>America/Los_Angeles</option><option>America/New_York</option><option>Europe/London</option><option>Asia/Kolkata</option></select></label><label>Capacity<input type="number" defaultValue={event?.capacity ?? 180} /></label><label>Locale<select defaultValue={event?.locale ?? "en-US"}><option>en-US</option><option>es-US</option><option>en-GB</option><option>en-IN</option></select></label><label>Registration channel<select defaultValue={event?.channel ?? "Public careers"}><option>Public careers</option><option>Campus QR</option><option>Talent community</option><option>Partner invitation</option></select></label><label>Owner<input defaultValue={event?.owner ?? "Priya Nair"} /></label><label className="full">Accessibility and support instructions<textarea defaultValue="Accessible venue, captions, quiet room and private adjustment route." /></label><label className="full checkbox-row"><input type="checkbox" defaultChecked />Event registration remains separate from applications and general recruiting authority.</label></div><button className="primary-button" type="submit">Save event version</button></form>}</section></HrShell>;
  }
  if (eventId && !event) return <HrShell title="Event unavailable" eyebrow={eventId} screenId="UI-HR-016" screen="high-volume"><OperationsNav /><section className="panel empty-state"><CalendarCheck2 size={28} /><h2>Recruiting event not found</h2><NavLink className="primary-button" to="/hr/events">Return to events</NavLink></section></HrShell>;
  if (event && checkIn) return <HrShell title={`${event.name} check-in`} eyebrow={`${event.id} · attendee operations`} screenId="UI-HR-016" screen="high-volume"><OperationsNav /><section className="panel"><div className="panel-heading"><div><h2>Registration, waitlist and attendance</h2><span>Event authority is not converted into an application or talent-community permission.</span></div><Pill tone="info">{checkedIn.length} checked in now</Pill></div><div className="table-toolbar"><label><Search size={16} /><input placeholder="Search ticket or attendee" /></label><button className="secondary-button" onClick={() => announce("QR scanner preview opened. No camera or attendee data was accessed.")}>Preview QR scanner</button></div><div className="event-attendee-grid">{attendees.map((attendee) => { const done = checkedIn.includes(attendee.id); return <article key={attendee.id}><div><strong>{attendee.name}</strong><small>{attendee.ticket} · {attendee.state}</small></div><span>{attendee.accessibility}</span><button disabled={attendee.state !== "Registered" || done} className="secondary-button" onClick={() => { setCheckedIn((current) => [...current, attendee.id]); announce(`${attendee.ticket} checked in with event-only authority.`); }}>{done ? "Checked in" : attendee.state === "Registered" ? "Check in" : attendee.state}</button></article>; })}</div></section></HrShell>;
  if (event) return <HrShell title={event.name} eyebrow={`${event.id} · ${event.type}`} screenId="UI-HR-016" screen="high-volume" actions={<><NavLink className="secondary-button" to={`/hr/events/${event.id}/edit`}>Edit version</NavLink><NavLink className="primary-button" to={`/hr/events/${event.id}/check-in`}>Open check-in</NavLink></>}><OperationsNav /><div className="system-detail-grid"><section className="panel record-detail-page"><div className="panel-heading"><div><span className="eyebrow">{event.locale} · {event.channel}</span><h2>{event.date}</h2></div><Pill tone={tone(event.status)}>{event.status}</Pill></div><section className="onboarding-metrics"><article><UsersRound size={19} /><span><strong>{event.registered}</strong>Registered</span></article><article><UserCheck size={19} /><span><strong>{event.checkedIn}</strong>Checked in</span></article><article><Clock3Icon /><span><strong>{event.waitlist}</strong>Waitlisted</span></article><article><Building2 size={19} /><span><strong>{event.capacity}</strong>Capacity</span></article></section><dl className="case-fact-grid"><div><dt>Owner</dt><dd>{event.owner}</dd></div><div><dt>Channel</dt><dd>{event.channel}</dd></div><div><dt>Locale</dt><dd>{event.locale}</dd></div><div><dt>Failure</dt><dd>{event.failure}</dd></div></dl><div className="detail-action-strip"><button className="primary-button" onClick={() => announce(`${event.id} publish-readiness preview passed capacity, content, locale and accessibility checks.`)}>Run publish readiness</button><button className="secondary-button" onClick={() => announce(`${event.id} attendee reminder preview excludes cancelled and event-authority-expired rows.`)}>Preview reminder</button><button className="secondary-button" onClick={() => announce(`${event.id} cancellation impact preview opened with notification and authority expiry.`)}>Preview cancellation</button></div></section><aside className="panel recovery-panel"><AlertTriangle size={23} /><h2>Embedded recovery</h2><p>Capacity, venue, content-version, notification and check-in failures retain the last safe event state.</p><ul><li>Freeze new registrations when full</li><li>Preserve waitlist order</li><li>Reconcile ticket business keys</li><li>Expire event-only authority on cancellation</li></ul></aside></div></HrShell>;
  const visible = recruitingEventAdmin.filter((item) => `${item.name} ${item.type} ${item.id}`.toLowerCase().includes(query.toLowerCase()));
  return <HrShell title="Recruiting event operations" eyebrow="Create, publish, register, check in and reconcile" screenId="UI-HR-016" screen="high-volume" actions={<NavLink className="primary-button" to="/hr/events/new"><Plus size={15} /> New event</NavLink>}><OperationsNav /><section className="panel lifecycle-table-panel"><div className="table-toolbar"><label><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search events" /></label><Pill tone="info">{visible.length} events</Pill></div><div className="operations-record-grid">{visible.map((item) => <NavLink to={`/hr/events/${item.id}`} key={item.id}><CalendarCheck2 size={21} /><span><small>{item.id} · {item.type}</small><strong>{item.name}</strong><em>{item.date} · {item.locale}</em></span><span><strong>{item.registered}/{item.capacity}</strong><small>{item.checkedIn} checked in · {item.waitlist} waitlist</small></span><Pill tone={tone(item.status)}>{item.status}</Pill></NavLink>)}</div></section></HrShell>;
}

function HighVolumeDetail() {
  const { campaignId, cohortId } = useParams();
  const { announce } = usePrototype();
  const campaign = highVolumeCampaigns.find((item) => item.id === campaignId);
  const cohort = highVolumeCohorts.find((item) => item.id === cohortId && item.campaignId === campaignId);
  const [bulkOpen, setBulkOpen] = useState(false);
  const [released, setReleased] = useState(false);
  if (!campaign) return <HrShell title="Campaign unavailable" eyebrow={campaignId ?? "Unknown"} screenId="UI-HR-017" screen="high-volume"><OperationsNav /><section className="panel empty-state"><UsersRound size={28} /><h2>High-volume campaign not found</h2><NavLink className="primary-button" to="/hr/high-volume">Return to campaigns</NavLink></section></HrShell>;
  if (cohortId && !cohort) return <HrShell title={campaign.name} eyebrow="Cohort unavailable" screenId="UI-HR-017" screen="high-volume"><OperationsNav /><section className="panel empty-state"><UsersRound size={28} /><h2>Cohort not found in this campaign</h2><NavLink className="primary-button" to={`/hr/high-volume/${campaign.id}`}>Return to campaign</NavLink></section></HrShell>;
  if (cohort) return <HrShell title={cohort.name} eyebrow={`${cohort.id} · ${campaign.name}`} screenId="UI-HR-017" screen="high-volume"><OperationsNav /><div className="system-detail-grid"><section className="panel record-detail-page"><div className="panel-heading"><div><span className="eyebrow">{cohort.campaignId} · owner {cohort.owner}</span><h2>{cohort.nextAction}</h2></div><Pill tone={tone(released ? "Active" : cohort.state)}>{released ? "Invitations released" : cohort.state}</Pill></div><section className="onboarding-metrics"><article><UsersRound size={19} /><span><strong>{cohort.applications}</strong>Applications</span></article><article><UserCheck size={19} /><span><strong>{cohort.ready}</strong>Ready</span></article><article><Building2 size={19} /><span><strong>{cohort.capacity}</strong>Capacity</span></article><article><AlertTriangle size={19} /><span><strong>{cohort.exceptions}</strong>Exceptions</span></article></section><button className="primary-button" onClick={() => setBulkOpen(true)}>Prepare bounded invitations</button>{bulkOpen && <div className="inline-confirm" role="alert"><strong>Release up to {Math.min(cohort.ready, cohort.capacity)} deterministic invitations?</strong><span>Only eligibility-complete rows are included. No ranking or candidate decision occurs.</span><div><button className="secondary-button" onClick={() => setBulkOpen(false)}>Cancel</button><button className="primary-button" onClick={() => { setReleased(true); setBulkOpen(false); announce(`${cohort.id} bounded invitations released in browser memory.`); }}>Confirm bounded release</button></div></div>}</section><aside className="panel recovery-panel"><AlertTriangle size={23} /><h2>Capacity and failure handling</h2><ul><li>Suppress duplicate business keys</li><li>Stop at human-review capacity</li><li>Create an exception for ineligible or stale rows</li><li>Reconcile partial delivery before retry</li></ul></aside></div></HrShell>;
  const cohorts = highVolumeCohorts.filter((item) => item.campaignId === campaign.id);
  return <HrShell title={campaign.name} eyebrow={`${campaign.id} · ${campaign.model}`} screenId="UI-HR-017" screen="high-volume"><OperationsNav /><section className="panel record-detail-page"><div className="panel-heading"><div><span className="eyebrow">Owner {campaign.owner}</span><h2>{campaign.stage}</h2><p>{campaign.automation}</p></div><Pill tone={tone(campaign.state)}>{campaign.state}</Pill></div><section className="onboarding-metrics"><article><Building2 size={19} /><span><strong>{campaign.jobs}</strong>Jobs</span></article><article><UsersRound size={19} /><span><strong>{campaign.applicants.toLocaleString()}</strong>Applicants</span></article><article><ClipboardCheck size={19} /><span><strong>{campaign.capacity}</strong>Human capacity</span></article><article><AlertTriangle size={19} /><span><strong>{campaign.exceptions}</strong>Exceptions</span></article></section><h2>Cohorts and bounded work</h2><div className="operations-record-grid">{cohorts.map((item) => <NavLink to={`/hr/high-volume/${campaign.id}/cohorts/${item.id}`} key={item.id}><UsersRound size={20} /><span><small>{item.id}</small><strong>{item.name}</strong><em>{item.nextAction}</em></span><span><strong>{item.ready}/{item.capacity}</strong><small>{item.exceptions} exceptions</small></span><Pill tone={tone(item.state)}>{item.state}</Pill></NavLink>)}</div></section></HrShell>;
}

function LocaleDetail() {
  const { localeId } = useParams();
  const location = useLocation();
  const { announce } = usePrototype();
  const item = localeVariants.find((row) => row.id === localeId);
  const editing = location.pathname.endsWith("/edit");
  const [saved, setSaved] = useState(false);
  const [approved, setApproved] = useState(false);
  if (!item) return <HrShell title="Locale pack unavailable" eyebrow={localeId ?? "Unknown"} screenId="UI-HR-018" screen="high-volume"><OperationsNav /><section className="panel empty-state"><Globe2 size={28} /><h2>Locale pack not found</h2><NavLink className="primary-button" to="/hr/locales">Return to locale packs</NavLink></section></HrShell>;
  if (editing) return <HrShell title={`Edit ${item.locale} content pack`} eyebrow={`${item.id} · versioned draft`} screenId="UI-HR-018" screen="high-volume"><OperationsNav /><section className="panel admin-form-page"><NavLink className="back-link" to={`/hr/locales/${item.id}`}><ArrowLeft size={15} /> Locale pack</NavLink>{saved ? <div className="completion-receipt"><CheckCircle2 size={23} /><div><strong>Draft locale version saved</strong><span>Legal/content approval remains required.</span></div></div> : <form className="portal-form" onSubmit={(e) => { e.preventDefault(); setSaved(true); announce(`${item.id} draft locale version saved in memory.`); }}><div className="form-grid"><label>Country<input defaultValue={item.country} /></label><label>Locale<input defaultValue={item.locale} /></label><label>Language<input defaultValue={item.language} /></label><label>Worker type<input defaultValue={item.workerType} /></label><label>Notice pack<input defaultValue={item.noticePack} /></label><label>Form pack<input defaultValue={item.formPack} /></label><label>Pay display<input defaultValue={item.payDisplay} /></label><label>Signature behavior<input defaultValue={item.signature} /></label><label className="full">Candidate preview copy<textarea defaultValue="Localized synthetic candidate and new-hire content preview." /></label></div><button className="primary-button" type="submit">Save draft version</button></form>}</section></HrShell>;
  return <HrShell title={`${item.country} · ${item.language}`} eyebrow={`${item.id} · ${item.workerType}`} screenId="UI-HR-018" screen="high-volume" actions={<NavLink className="secondary-button" to={`/hr/locales/${item.id}/edit`}>Edit draft</NavLink>}><OperationsNav /><div className="system-detail-grid"><section className="panel record-detail-page"><div className="panel-heading"><div><span className="eyebrow">{item.locale}</span><h2>Candidate and onboarding content pack</h2></div><Pill tone={tone(approved ? "Approved demo" : item.reviewState)}>{approved ? "Approved demo" : item.reviewState}</Pill></div><dl className="case-fact-grid"><div><dt>Notice</dt><dd>{item.noticePack}</dd></div><div><dt>Forms</dt><dd>{item.formPack}</dd></div><div><dt>Pay</dt><dd>{item.payDisplay}</dd></div><div><dt>Signature</dt><dd>{item.signature}</dd></div><div><dt>Fallback</dt><dd>Block if approved localized content is unavailable</dd></div><div><dt>Effective scope</dt><dd>{item.country} · {item.workerType}</dd></div></dl><section className="locale-preview" lang={item.locale.split("-")[0]}><span className="eyebrow">Candidate preview</span><h2>{item.language} content rendering</h2><p>All navigation, notice, error, support, form, communication and accessible-document content must be complete before activation.</p></section><div className="detail-action-strip"><button className="primary-button" onClick={() => { setApproved(true); announce(`${item.id} synthetic approval recorded; legal approval is still not claimed.`); }}>Approve demo version</button><button className="secondary-button" onClick={() => announce(`${item.id} route-by-route locale preview opened across candidate and onboarding screens.`)}>Run screen preview</button></div></section><aside className="panel recovery-panel"><AlertTriangle size={23} /><h2>Missing-content behavior</h2><p>An incomplete or conflicting pack blocks publication, collection and signature rather than silently falling back.</p></aside></div></HrShell>;
}

function RecoveryDetail() {
  const { recoveryId } = useParams();
  const { announce } = usePrototype();
  const item = recoveryScenarios.find((row) => row.id === recoveryId);
  const [state, setState] = useState(item?.state ?? "Open");
  const [evidence, setEvidence] = useState<string[]>([]);
  if (!item) return <HrShell title="Recovery case unavailable" eyebrow={recoveryId ?? "Unknown"} screenId="UI-HR-019" screen="high-volume"><OperationsNav /><section className="panel empty-state"><RefreshCcw size={28} /><h2>Recovery case not found</h2><NavLink className="primary-button" to="/hr/recovery">Return to recovery</NavLink></section></HrShell>;
  const addEvidence = (label: string) => { setEvidence((current) => current.includes(label) ? current : [...current, label]); announce(`${item.id} ${label.toLowerCase()} evidence added in browser memory.`); };
  return <HrShell title={`${item.journey} recovery`} eyebrow={`${item.id} · ${item.failure}`} screenId="UI-HR-019" screen="high-volume"><OperationsNav /><div className="system-detail-grid"><section className="panel record-detail-page"><div className="panel-heading"><div><span className="eyebrow">Owner {item.owner} · attempt {item.attempts}</span><h2>{item.safeState}</h2></div><Pill tone={tone(state)}>{state}</Pill></div><dl className="case-fact-grid"><div><dt>Failure</dt><dd>{item.failure}</dd></div><div><dt>Safe state</dt><dd>{item.safeState}</dd></div><div><dt>Recovery</dt><dd>{item.recovery}</dd></div><div><dt>Idempotency</dt><dd>{item.idempotencyKey}</dd></div></dl><h2>Recovery evidence</h2><div className="evidence-checklist">{["Source state captured", "Destination checked", "Impact preview approved", "Retry receipt reconciled"].map((label) => <label key={label}><input type="checkbox" checked={evidence.includes(label)} onChange={() => addEvidence(label)} />{label}</label>)}</div><div className="detail-action-strip"><button disabled={state === "Resolved" || evidence.length < 3} className="primary-button" onClick={() => { setState("Recovering"); announce(`${item.id} recovery replayed with the same business key.`); }}>Retry safely</button><button className="secondary-button" onClick={() => { setState("Cancelled"); announce(`${item.id} cancelled with compensating-work preview.`); }}>Cancel downstream work</button><button disabled={evidence.length < 4} className="secondary-button" onClick={() => { setState("Resolved"); announce(`${item.id} resolved with complete reconciliation evidence.`); }}>Resolve case</button></div></section><aside className="panel recovery-panel"><ShieldCheck size={23} /><h2>Invariant</h2><p>Retry never creates a duplicate candidate, invitation, meeting, offer, worker, account, asset or application.</p></aside></div></HrShell>;
}

function AgencyAssignments() {
  const { assignmentId } = useParams();
  const location = useLocation();
  const { announce } = usePrototype();
  const item = agencyAssignments.find((row) => row.id === assignmentId);
  const creating = location.pathname.endsWith("/new");
  const editing = location.pathname.endsWith("/edit");
  const partners = location.pathname.endsWith("/partners");
  const [saved, setSaved] = useState(false);
  const [dispute, setDispute] = useState(false);
  const [query, setQuery] = useState("");
  if (partners) return <HrShell title="Agency partners" eyebrow="Partner users, assignments and access" screenId="UI-HR-020" screen="talent"><OperationsNav /><section className="panel"><div className="panel-heading"><div><h2>Approved partner accounts</h2><span>Assignment and effective-date scope is rechecked at every destination.</span></div><button className="primary-button" onClick={() => announce("Partner invitation form opened with MFA, assignment, locale and expiry fields.")}>Invite partner user</button></div><div className="agency-partner-grid">{["Northstar Product Search", "Synthetic Engineering Partners", "Beacon People Advisory", "Atlas Finance Talent"].map((agency, index) => <article key={agency}><Building2 size={22} /><h3>{agency}</h3><p>{1 + index} active users · {agencyAssignments.filter((a) => a.agency === agency && a.status === "Active").length} active assignments</p><Pill tone={index === 2 ? "warning" : "success"}>{index === 2 ? "Access review due" : "MFA verified"}</Pill><button className="secondary-button" onClick={() => announce(`${agency} partner-access review opened with assignment and expiry evidence.`)}>Review access</button></article>)}</div></section></HrShell>;
  if (creating || editing) return <HrShell title={creating ? "Create agency assignment" : `Edit ${item?.id ?? "assignment"}`} eyebrow="Commercial and access contract" screenId="UI-HR-020" screen="talent"><OperationsNav /><section className="panel admin-form-page"><NavLink className="back-link" to={item ? `/hr/agency-assignments/${item.id}` : "/hr/agency-assignments"}><ArrowLeft size={15} /> Agency assignments</NavLink>{saved ? <div className="completion-receipt"><CheckCircle2 size={23} /><div><strong>{creating ? "Assignment AGA-MEM-001 created" : "Assignment version saved"}</strong><span>Partner access remains bounded by effective dates and job scope.</span></div></div> : <form className="portal-form" onSubmit={(e) => { e.preventDefault(); setSaved(true); announce("Agency assignment saved in browser memory."); }}><div className="form-grid"><label>Agency<select defaultValue={item?.agency ?? "Northstar Product Search"}>{[...new Set(agencyAssignments.map((a) => a.agency))].map((agency) => <option key={agency}>{agency}</option>)}</select></label><label>Job<input defaultValue={item?.job ?? "Senior Product Designer"} /></label><label>Openings<input type="number" defaultValue={item?.openings ?? 1} /></label><label>Fee schedule<input defaultValue={item?.fee ?? "20% first-year base"} /></label><label>Effective from<input type="date" defaultValue={item?.start ?? "2026-08-28"} /></label><label>Effective through<input type="date" defaultValue={item?.end ?? "2026-10-31"} /></label><label>Regions<input defaultValue={item?.regions ?? "US-CA · Remote"} /></label><label>Terms version<input defaultValue={item?.termsVersion ?? "AGENCY-TERMS-v4"} /></label><label className="full checkbox-row"><input type="checkbox" defaultChecked />Require candidate authorization and safe duplicate matching for every submission.</label></div><button className="primary-button" type="submit">Save assignment</button></form>}</section></HrShell>;
  if (assignmentId && !item) return <HrShell title="Assignment unavailable" eyebrow={assignmentId} screenId="UI-HR-020" screen="talent"><OperationsNav /><section className="panel empty-state"><Handshake size={28} /><h2>Agency assignment not found</h2><NavLink className="primary-button" to="/hr/agency-assignments">Return to assignments</NavLink></section></HrShell>;
  if (item) return <HrShell title={item.job} eyebrow={`${item.id} · ${item.agency}`} screenId="UI-HR-020" screen="talent" actions={<NavLink className="secondary-button" to={`/hr/agency-assignments/${item.id}/edit`}>Edit assignment</NavLink>}><OperationsNav /><div className="system-detail-grid"><section className="panel record-detail-page"><div className="panel-heading"><div><span className="eyebrow">{item.regions} · {item.termsVersion}</span><h2>{item.openings} openings · {item.fee}</h2></div><Pill tone={tone(item.status)}>{item.status}</Pill></div><dl className="case-fact-grid"><div><dt>Effective</dt><dd>{item.start}–{item.end}</dd></div><div><dt>Submissions</dt><dd>{item.submissions}</dd></div><div><dt>Owner</dt><dd>{item.owner}</dd></div><div><dt>Duplicate behavior</dt><dd>Safe match reference only</dd></div><div><dt>Candidate notice</dt><dd>Required before submission</dd></div><div><dt>Withdrawal</dt><dd>Agency can withdraw its owned submission</dd></div></dl><button className="primary-button" onClick={() => { setDispute(true); announce(`${item.id} fee/ownership dispute opened without changing candidate review.`); }}>Open fee or ownership dispute</button>{dispute && <div className="inline-confirm" role="status"><strong>Dispute AGD-MEM-001 opened</strong><span>Commercial credit is paused; candidate review remains independent.</span></div>}</section><aside className="panel recovery-panel"><AlertTriangle size={23} /><h2>Failure and expiry</h2><ul><li>Expired assignment blocks new submissions</li><li>Duplicate candidate identity remains masked</li><li>Fee disputes do not block candidate review</li><li>Partner access is revoked at effective end</li></ul></aside></div></HrShell>;
  const visible = agencyAssignments.filter((row) => `${row.agency} ${row.job} ${row.id}`.toLowerCase().includes(query.toLowerCase()));
  return <HrShell title="Agency assignment operations" eyebrow="Partners, terms, access, ownership and fees" screenId="UI-HR-020" screen="talent" actions={<><NavLink className="secondary-button" to="/hr/agency-assignments/partners">Partner users</NavLink><NavLink className="primary-button" to="/hr/agency-assignments/new"><Plus size={15} /> New assignment</NavLink></>}><OperationsNav /><section className="panel lifecycle-table-panel"><div className="table-toolbar"><label><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search agency, job or assignment" /></label><Pill tone="info">{visible.length} assignments</Pill></div><div className="operations-record-grid">{visible.map((row) => <NavLink to={`/hr/agency-assignments/${row.id}`} key={row.id}><Handshake size={20} /><span><small>{row.id} · {row.agency}</small><strong>{row.job}</strong><em>{row.regions} · {row.termsVersion}</em></span><span><strong>{row.fee}</strong><small>{row.submissions} submissions</small></span><Pill tone={tone(row.status)}>{row.status}</Pill></NavLink>)}</div></section></HrShell>;
}

function Clock3Icon() { return <span aria-hidden="true">◷</span>; }

export function RecruitingOperationsV3() {
  const path = useLocation().pathname;
  if (path.startsWith("/hr/events")) return <EventOperations />;
  if (path.startsWith("/hr/agency-assignments")) return <AgencyAssignments />;
  if (path.startsWith("/hr/locales/")) return <LocaleDetail />;
  if (path.startsWith("/hr/recovery/")) return <RecoveryDetail />;
  if (path.endsWith("/planning") || path.endsWith("/analytics")) return <HighVolumePlanning />;
  return <HighVolumeDetail />;
}
