import { useMemo, useState } from "react";
import { NavLink, useLocation, useParams } from "react-router-dom";
import { AlertTriangle, ArrowLeft, Bell, Building2, CheckCircle2, ClipboardCheck, FileCheck2, Handshake, Laptop, LockKeyhole, PackageCheck, Plus, Search, ShieldCheck, UserRoundCheck, UsersRound } from "lucide-react";
import { agencySubmissions } from "../data/lifecycleDepth";
import { newHireRecords, onboardingCheckIns, provisioningRequests } from "../data/onboarding";
import { Pill, PrototypeBanner, ScreenId } from "./Common";
import { usePrototype } from "../prototype/PrototypeContext";

type PortalKind = "manager" | "it" | "agency";

const portalLabels = {
  manager: { title: "Manager readiness", subtitle: "Your team transitions", badge: "Manager-scoped synthetic portal" },
  it: { title: "Workplace fulfilment", subtitle: "IT and access readiness", badge: "IT-scoped synthetic portal" },
  agency: { title: "Approved agency portal", subtitle: "Assignments and submissions", badge: "Agency-scoped synthetic portal" },
};

function PortalShell({ kind, children }: { kind: PortalKind; children: React.ReactNode }) {
  const label = portalLabels[kind];
  return <div className={`role-portal ${kind}-portal`}><PrototypeBanner /><header className="role-portal-header"><NavLink className="role-portal-brand" to={`/${kind}`}><span className="role-portal-mark">{kind === "manager" ? <UserRoundCheck size={22} /> : kind === "it" ? <Laptop size={22} /> : <Handshake size={22} />}</span><span><strong>{label.title}</strong><small>{label.subtitle}</small></span></NavLink><nav aria-label={`${label.title} navigation`}><NavLink end to={`/${kind}`}>Home</NavLink>{kind === "agency" && <NavLink to="/agency/submissions">Submissions</NavLink>}<a href="#role-support">Support</a></nav><Pill tone="info">{label.badge}</Pill></header><main id="main-content" className="role-portal-main">{children}</main><footer id="role-support" className="role-portal-footer"><ShieldCheck size={18} /><span><strong>Synthetic role portal</strong>No sign-in, provider connection, message, account, asset or record write exists.</span></footer></div>;
}

function ManagerPortal() {
  const { newHireId } = useParams();
  const { announce } = usePrototype();
  const manager = "Marcus Johnson";
  const hires = newHireRecords.filter((item) => item.manager === manager);
  const selected = hires.find((item) => item.id === newHireId);
  const [completed, setCompleted] = useState<string[]>([]);
  if (newHireId && !selected) return <PortalShell kind="manager"><section className="role-access-denied"><LockKeyhole size={28} /><h1>New hire is outside this manager relationship</h1><p>Direct URL access does not expand the seeded reporting line.</p><NavLink className="primary-button" to="/manager">Return to your team</NavLink></section></PortalShell>;
  if (selected) {
    const checks = onboardingCheckIns.filter((item) => item.newHireId === selected.id).slice(0, 5);
    return <PortalShell kind="manager"><NavLink className="back-link" to="/manager"><ArrowLeft size={15} /> Your team</NavLink><section className="role-portal-hero compact"><div><ScreenId>UI-MGR-001</ScreenId><span className="eyebrow">{selected.id} · starts {selected.startDateShort}</span><h1>{selected.name}</h1><p>{selected.role} · {selected.location}</p></div><Pill tone={selected.risk === "At risk" ? "danger" : "success"}>{selected.risk}</Pill></section><div className="role-dashboard-grid"><section className="panel"><h2>Manager commitments</h2><div className="portal-task-list">{["Confirm first-week goals", "Publish day-one agenda", "Schedule weekly check-ins", "Introduce buddy and team"].map((task, index) => { const id = `MGR-${index + 1}`; const done = completed.includes(id); return <article key={id}><span>{done ? <CheckCircle2 size={20} /> : <ClipboardCheck size={20} />}</span><div><strong>{task}</strong><small>Due before {index < 2 ? "day one" : `day ${30 + index * 15}`}</small></div><button disabled={done} onClick={() => { setCompleted((current) => [...current, id]); announce(`${task} completed in manager portal memory.`); }}>{done ? "Complete" : "Mark complete"}</button></article>; })}</div></section><section className="panel"><h2>30/60/90 check-ins</h2><div className="checkin-list">{checks.map((item) => <article key={item.id}><div><strong>{item.milestone}</strong><small>{item.id} · due {item.due}</small><span>{item.goal}</span></div><Pill tone={item.state === "Overdue" ? "danger" : item.state === "Complete" ? "success" : "info"}>{item.state}</Pill></article>)}</div></section><aside className="panel manager-privacy"><LockKeyhole size={22} /><h2>Manager-safe boundary</h2><p>You can see readiness commitments, goals and operational blockers. Private forms, tax, work authorization, recruiting feedback and accommodation details remain hidden.</p><button className="secondary-button" onClick={() => announce("People Operations support request opened with manager-safe context only.")}>Request People Ops help</button></aside></div></PortalShell>;
  }
  return <PortalShell kind="manager"><section className="role-portal-hero"><div><ScreenId>UI-MGR-001</ScreenId><span className="eyebrow">Welcome, Marcus</span><h1>Make every start intentional.</h1><p>See only your effective reports and the readiness work you own.</p></div><Pill tone="success">{hires.length} new hire in scope</Pill></section><section className="role-summary-cards"><article><UsersRound size={22} /><strong>{hires.length}</strong><span>Starting soon</span></article><article><ClipboardCheck size={22} /><strong>4</strong><span>Manager tasks</span></article><article><Bell size={22} /><strong>1</strong><span>Due this week</span></article><article><CheckCircle2 size={22} /><strong>75%</strong><span>Readiness</span></article></section><section className="panel role-record-list"><div className="panel-heading"><div><h2>Your incoming team members</h2><span>Relationship-scoped and effective-dated</span></div></div>{hires.map((item) => <NavLink to={`/manager/new-hires/${item.id}`} key={item.id}><span className="candidate-avatar">{item.initials}</span><span><strong>{item.name}</strong><small>{item.role} · starts {item.startDateShort}</small></span><span><strong>{item.progress}%</strong><small>plan complete</small></span><Pill tone={item.risk === "At risk" ? "danger" : "success"}>{item.risk}</Pill></NavLink>)}</section></PortalShell>;
}

function ItPortal() {
  const { requestId } = useParams();
  const { announce } = usePrototype();
  const [delivered, setDelivered] = useState<string[]>([]);
  const itRequests = provisioningRequests.filter((item) => item.function === "IT");
  const selected = itRequests.find((item) => item.id === requestId);
  if (requestId && !selected) return <PortalShell kind="it"><section className="role-access-denied"><AlertTriangle size={28} /><h1>Request unavailable</h1><p>The request may belong to another fulfilment function or no longer be active.</p><NavLink className="primary-button" to="/it">Return to queue</NavLink></section></PortalShell>;
  if (selected) {
    const state = delivered.includes(selected.id) ? "Delivered" : selected.status;
    return <PortalShell kind="it"><NavLink className="back-link" to="/it"><ArrowLeft size={15} /> IT queue</NavLink><section className="role-portal-hero compact"><div><ScreenId>UI-IT-001</ScreenId><span className="eyebrow">{selected.id} · {selected.newHireId}</span><h1>{selected.item}</h1><p>For {selected.newHire} · owner {selected.owner}</p></div><Pill tone={state === "Blocked" ? "danger" : state === "Delivered" ? "success" : "info"}>{state}</Pill></section><div className="role-dashboard-grid"><section className="panel"><h2>Fulfilment contract</h2><dl className="case-fact-grid"><div><dt>Effective date</dt><dd>{selected.due}</dd></div><div><dt>Dependency</dt><dd>{selected.dependency ?? "Approved worker and role bundle"}</dd></div><div><dt>Least privilege</dt><dd>RBAC bundle IT-US-v6</dd></div><div><dt>Reconciliation</dt><dd>{state === "Delivered" ? "Synthetic receipt REC-IT-001" : "Awaiting effect"}</dd></div><div><dt>Cancellation</dt><dd>Revocation work generated if start is cancelled</dd></div><div><dt>Restricted data</dt><dd>No recruiting feedback or private forms</dd></div></dl><div className="detail-action-strip"><button disabled={state === "Blocked" || state === "Delivered"} className="primary-button" onClick={() => { setDelivered((current) => [...current, selected.id]); announce(`${selected.id} marked delivered in browser memory with synthetic reconciliation evidence.`); }}>Mark delivered</button><button className="secondary-button" onClick={() => announce(`${selected.id} retry preview opened with the same idempotency key.`)}>Retry safely</button><button className="secondary-button" onClick={() => announce(`${selected.id} cancellation impact preview opened; no account was revoked.`)}>Preview cancellation</button></div></section><aside className="panel"><PackageCheck size={24} /><h2>Evidence before completion</h2><ul><li>Destination effect ID</li><li>Approved role/access bundle version</li><li>Delivery or activation timestamp</li><li>Reconciliation checksum</li><li>Revocation owner and due date</li></ul></aside></div></PortalShell>;
  }
  return <PortalShell kind="it"><section className="role-portal-hero"><div><ScreenId>UI-IT-001</ScreenId><span className="eyebrow">IT Operations</span><h1>Ready on time. Least privilege by default.</h1><p>Work only the requests, dependencies and evidence needed for fulfilment.</p></div><Pill tone="info">{itRequests.length} IT requests</Pill></section><section className="role-summary-cards"><article><Laptop size={22} /><strong>{itRequests.length}</strong><span>IT requests</span></article><article><AlertTriangle size={22} /><strong>{itRequests.filter((item) => item.status === "Blocked").length}</strong><span>Blocked</span></article><article><PackageCheck size={22} /><strong>{itRequests.filter((item) => item.status === "Ready").length}</strong><span>Ready to deliver</span></article><article><ShieldCheck size={22} /><strong>v6</strong><span>Role bundle</span></article></section><section className="panel role-record-list"><div className="panel-heading"><div><h2>Fulfilment queue</h2><span>IT-only requests; candidate and recruiting detail minimized</span></div></div>{itRequests.slice(0, 18).map((item) => <NavLink to={`/it/requests/${item.id}`} key={item.id}><span className="role-portal-record-icon"><Laptop size={18} /></span><span><strong>{item.item}</strong><small>{item.id} · {item.newHire} · due {item.due}</small></span><span><strong>{item.owner}</strong><small>{item.dependency ?? "No blocker"}</small></span><Pill tone={item.status === "Blocked" ? "danger" : item.status === "Delivered" ? "success" : "info"}>{item.status}</Pill></NavLink>)}</section></PortalShell>;
}

function AgencyPortal() {
  const location = useLocation();
  const { submissionId } = useParams();
  const { announce } = usePrototype();
  const [query, setQuery] = useState("");
  const [created, setCreated] = useState(false);
  const scoped = useMemo(() => agencySubmissions.filter((item) => item.agency === "Northstar Product Search" && `${item.candidate} ${item.job} ${item.id}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const selected = agencySubmissions.find((item) => item.id === submissionId && item.agency === "Northstar Product Search");
  if (location.pathname.endsWith("/new")) return <PortalShell kind="agency"><NavLink className="back-link" to="/agency/submissions"><ArrowLeft size={15} /> Submissions</NavLink><section className="panel agency-submission-form"><ScreenId>UI-AGY-001</ScreenId><span className="eyebrow">New candidate submission</span><h1>Validate ownership before creating an application.</h1>{created ? <div className="completion-receipt"><CheckCircle2 size={24} /><div><strong>Submission AGS-MEM-001 created</strong><span>Validation state · no candidate or application record created</span></div></div> : <form onSubmit={(event) => { event.preventDefault(); setCreated(true); announce("Agency submission AGS-MEM-001 created in validation state in browser memory."); }}><div className="form-grid"><label>Assigned job<select><option>Senior Product Designer · AGA-DEMO-001</option><option>Product Design Manager · AGA-DEMO-004</option></select></label><label>Candidate fixture<select><option>Maya Chen · synthetic</option><option>Noah Williams · synthetic</option></select></label><label>Candidate notice version<input defaultValue="AGENCY-NOTICE-v4" /></label><label>Source date<input defaultValue="2026-08-28" type="date" /></label><label>Ownership evidence<select><option>Candidate authorization received</option><option>Prior relationship evidence</option></select></label><label>Fee schedule<input defaultValue="20% first-year base" /></label></div><div className="field-assurance"><LockKeyhole size={16} />Duplicate checks return a safe reference only; they never reveal another agency or recruiter owner.</div><button className="primary-button" type="submit">Submit to validation</button></form>}</section></PortalShell>;
  if (submissionId) {
    if (!selected) return <PortalShell kind="agency"><section className="role-access-denied"><LockKeyhole size={28} /><h1>Submission outside this agency scope</h1><p>Direct URLs cannot expose another partner’s candidate, fee or ownership claim.</p><NavLink className="primary-button" to="/agency/submissions">Return to submissions</NavLink></section></PortalShell>;
    return <PortalShell kind="agency"><NavLink className="back-link" to="/agency/submissions"><ArrowLeft size={15} /> Submissions</NavLink><section className="role-portal-hero compact"><div><ScreenId>UI-AGY-001</ScreenId><span className="eyebrow">{selected.id} · {selected.assignment}</span><h1>{selected.candidate}</h1><p>{selected.job}</p></div><Pill tone={selected.state === "Duplicate" || selected.state === "Ownership review" ? "warning" : selected.state === "Accepted" ? "success" : "info"}>{selected.state}</Pill></section><div className="role-dashboard-grid"><section className="panel"><h2>Submission contract</h2><dl className="case-fact-grid"><div><dt>Ownership window</dt><dd>{selected.ownershipWindow}</dd></div><div><dt>Fee</dt><dd>{selected.fee}</dd></div><div><dt>Duplicate reference</dt><dd>{selected.duplicateOf}</dd></div><div><dt>Next action</dt><dd>{selected.nextAction}</dd></div><div><dt>Candidate notice</dt><dd>AGENCY-NOTICE-v4</dd></div><div><dt>Application</dt><dd>{selected.state === "Accepted" ? "Separate application may be created" : "Not created"}</dd></div></dl><button className="secondary-button" onClick={() => announce(`${selected.id} message composer opened; no message was sent.`)}>Message recruiting team</button></section><aside className="panel"><FileCheck2 size={24} /><h2>Ownership and duplicate rules</h2><ul><li>Candidate authorization is required</li><li>Assignment must be current for the job</li><li>Existing identity is returned as a safe match only</li><li>Fee disputes pause commercial credit, not candidate review</li></ul></aside></div></PortalShell>;
  }
  if (location.pathname.includes("/submissions")) return <PortalShell kind="agency"><section className="role-portal-hero compact"><div><ScreenId>UI-AGY-001</ScreenId><span className="eyebrow">Northstar Product Search</span><h1>Your candidate submissions</h1><p>Only candidates and assignments owned by this synthetic agency are visible.</p></div><NavLink className="primary-button" to="/agency/submissions/new"><Plus size={16} /> New submission</NavLink></section><section className="panel role-record-list"><div className="table-toolbar"><label><Search size={16} /><input aria-label="Search agency submissions" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search candidate, job or ID" /></label><Pill tone="info">{scoped.length} scoped submissions</Pill></div>{scoped.map((item) => <NavLink to={`/agency/submissions/${item.id}`} key={item.id}><span className="role-portal-record-icon"><Handshake size={18} /></span><span><strong>{item.candidate}</strong><small>{item.id} · {item.job}</small></span><span><strong>{item.fee}</strong><small>{item.ownershipWindow}</small></span><Pill tone={item.state === "Duplicate" || item.state === "Ownership review" ? "warning" : item.state === "Accepted" ? "success" : "info"}>{item.state}</Pill></NavLink>)}</section></PortalShell>;
  return <PortalShell kind="agency"><section className="role-portal-hero"><div><ScreenId>UI-AGY-001</ScreenId><span className="eyebrow">Northstar Product Search</span><h1>Submit with consent. Resolve ownership fairly.</h1><p>Assignments, duplicate checks, candidate notices and fee evidence remain explicit.</p></div><NavLink className="primary-button" to="/agency/submissions">Open submissions</NavLink></section><section className="role-summary-cards"><article><Building2 size={22} /><strong>4</strong><span>Open assignments</span></article><article><UsersRound size={22} /><strong>{scoped.length}</strong><span>Scoped submissions</span></article><article><AlertTriangle size={22} /><strong>{scoped.filter((item) => item.state === "Duplicate" || item.state === "Ownership review").length}</strong><span>Ownership reviews</span></article><article><CheckCircle2 size={22} /><strong>{scoped.filter((item) => item.state === "Accepted").length}</strong><span>Accepted</span></article></section></PortalShell>;
}

export function RolePortal({ kind }: { kind: PortalKind }) {
  if (kind === "manager") return <ManagerPortal />;
  if (kind === "it") return <ItPortal />;
  return <AgencyPortal />;
}
